'use strict';
const express = require('express');
const router = express.Router();
const verifyShopifySession = require('../../middleware/verifyShopifySession');
const { requireCreditsOnMutation } = require('../../core/creditMiddleware');
const ah = fn => (req, res, next) => Promise.resolve(fn(req, res, next)).catch(next);
router.use(verifyShopifySession);
router.get('/health', ah(async (req, res) => res.json({ ok: true, service: 'conditional-logic-automation', v: '2.0.0' })));
const engine = require('./engines/conditional-logic-engine');
router.get('/dashboard', ah(async (req, res) => res.json({ ok: true, ...engine.getDashboardStats() })));
router.get('/rules', ah(async (req, res) => res.json({ ok: true, rules: engine.getRuleTrees(req.query) })));
router.get('/rules/:id', ah(async (req, res) => { const r = engine.getRuleTree(req.params.id); if (!r) return res.status(404).json({ ok: false, error: 'not found' }); res.json({ ok: true, rule: r }); }));
router.get('/fields', ah(async (req, res) => res.json({ ok: true, fields: engine.getConditionFields() })));
router.use((err, req, res, next) => res.status(500).json({ ok: false, error: err.message }));
module.exports = router;
