'use strict';
const express = require('express');
const router = express.Router();
const verifyShopifySession = require('../../middleware/verifyShopifySession');
const { requireCreditsOnMutation } = require('../../core/creditMiddleware');
const ah = fn => (req, res, next) => Promise.resolve(fn(req, res, next)).catch(next);
router.use(verifyShopifySession);
const engine = require('./engines/conditional-logic-engine');
router.get('/health', ah(async (req, res) => res.json({ ok: true, service: 'conditional-logic-automation', v: '2.0.0' })));
router.get('/dashboard', ah(async (req, res) => res.json({ ok: true, ...engine.getDashboardStats() })));
router.get('/condition-fields', ah(async (req, res) => res.json({ ok: true, ...engine.getConditionFields() })));
router.get('/rule-trees', ah(async (req, res) => res.json({ ok: true, ...engine.getRuleTrees(req.query) })));
router.get('/rule-trees/:id', ah(async (req, res) => { const item = engine.getRuleTree(req.params.id); if (!item) return res.status(404).json({ ok: false, error: 'not found' }); res.json({ ok: true, tree: item }); }));
router.post('/rule-trees/evaluate', ah(async (req, res) => res.json({ ok: true, ...engine.evaluateTree(req.body) })));
router.post('/segment/preview', ah(async (req, res) => res.json({ ok: true, ...engine.previewSegment(req.body) })));
router.use((err, req, res, next) => res.status(500).json({ ok: false, error: err.message }));
module.exports = router;
