'use strict';
const express = require('express');
const router = express.Router();
const verifyShopifySession = require('../../middleware/verifyShopifySession');
const { requireCreditsOnMutation } = require('../../core/creditMiddleware');
const ah = fn => (req, res, next) => Promise.resolve(fn(req, res, next)).catch(next);
router.use(verifyShopifySession);
router.get('/health', ah(async (req, res) => res.json({ ok: true, service: 'custom-dashboard-builder', v: '2.0.0' })));
const engine = require('./engines/dashboard-builder-engine');
router.get('/dashboard', ah(async (req, res) => res.json({ ok: true, ...engine.getDashboardStats() })));
router.get('/dashboards', ah(async (req, res) => res.json({ ok: true, dashboards: engine.getDashboards(req.query) })));
router.get('/dashboards/:id', ah(async (req, res) => { const d = engine.getDashboard(req.params.id); if (!d) return res.status(404).json({ ok: false, error: 'not found' }); res.json({ ok: true, dashboard: d }); }));
router.get('/widgets/catalog', ah(async (req, res) => res.json({ ok: true, catalog: engine.getWidgetCatalog(req.query) })));
router.get('/widgets/:id/data', ah(async (req, res) => { res.json({ ok: true, ...engine.getWidgetData(req.params.id) }); }));
router.use((err, req, res, next) => res.status(500).json({ ok: false, error: err.message }));
module.exports = router;
