'use strict';
const express = require('express');
const router = express.Router();
const verifyShopifySession = require('../../middleware/verifyShopifySession');
const { requireCreditsOnMutation } = require('../../core/creditMiddleware');
const ah = fn => (req, res, next) => Promise.resolve(fn(req, res, next)).catch(next);
router.use(verifyShopifySession);
const engine = require('./engines/workflow-automation-engine');
router.get('/health', ah(async (req, res) => res.json({ ok: true, service: 'workflow-automation-builder', v: '2.0.0' })));
router.get('/dashboard', ah(async (req, res) => res.json({ ok: true, ...engine.getDashboardStats() })));
router.get('/triggers', ah(async (req, res) => res.json({ ok: true, triggers: engine.getTriggers() })));
router.get('/actions', ah(async (req, res) => res.json({ ok: true, actions: engine.getActions() })));
router.get('/rules', ah(async (req, res) => res.json({ ok: true, ...engine.getRules(req.query) })));
router.get('/rules/:id', ah(async (req, res) => { const item = engine.getRule(req.params.id); if (!item) return res.status(404).json({ ok: false, error: 'not found' }); res.json({ ok: true, rule: item }); }));
router.post('/rules/parse', ah(async (req, res) => res.json({ ok: true, ...engine.parseRule(req.body) })));
router.post('/rules/test', ah(async (req, res) => res.json({ ok: true, ...engine.testRule(req.body) })));
router.post('/automations/suggest', requireCreditsOnMutation('content-brief'), ah(async (req, res) => res.json({ ok: true, ...engine.suggestAutomations(req.body) })));
router.use((err, req, res, next) => res.status(500).json({ ok: false, error: err.message }));
module.exports = router;
