'use strict';
const express = require('express');
const router = express.Router();
const verifyShopifySession = require('../../middleware/verifyShopifySession');
const { requireCreditsOnMutation } = require('../../core/creditMiddleware');
const ah = fn => (req, res, next) => Promise.resolve(fn(req, res, next)).catch(next);
router.use(verifyShopifySession);
const engine = require('./engines/collaboration-approval-engine');
router.get('/health', ah(async (req, res) => res.json({ ok: true, service: 'collaboration-approval-workflows', v: '2.0.0' })));
router.get('/dashboard', ah(async (req, res) => res.json({ ok: true, ...engine.getDashboardStats() })));
router.get('/chains', ah(async (req, res) => res.json({ ok: true, chains: engine.getChains() })));
router.get('/audit-log', ah(async (req, res) => res.json({ ok: true, ...engine.getAuditLog(req.query) })));
router.get('/requests', ah(async (req, res) => res.json({ ok: true, ...engine.getRequests(req.query) })));
router.get('/requests/:id', ah(async (req, res) => { const item = engine.getRequest(req.params.id); if (!item) return res.status(404).json({ ok: false, error: 'not found' }); res.json({ ok: true, request: item }); }));
router.post('/requests/:id/approve', ah(async (req, res) => res.json({ ok: true, ...engine.approveRequest(req.params.id, req.body) })));
router.post('/requests/:id/reject', ah(async (req, res) => res.json({ ok: true, ...engine.rejectRequest(req.params.id, req.body) })));
router.post('/requests/:id/delegate', ah(async (req, res) => res.json({ ok: true, ...engine.delegateApproval(req.params.id, req.body) })));
router.use((err, req, res, next) => res.status(500).json({ ok: false, error: err.message }));
module.exports = router;

