'use strict';
const express = require('express');
const router = express.Router();
const verifyShopifySession = require('../../middleware/verifyShopifySession');
const { requireCreditsOnMutation } = require('../../core/creditMiddleware');
const ah = fn => (req, res, next) => Promise.resolve(fn(req, res, next)).catch(next);
router.use(verifyShopifySession);
router.get('/health', ah(async (req, res) => res.json({ ok: true, service: 'collaboration-approval-workflows', v: '2.0.0' })));
const engine = require('./engines/collaboration-approval-engine');
router.get('/dashboard', ah(async (req, res) => res.json({ ok: true, ...engine.getDashboardStats() })));
router.get('/requests', ah(async (req, res) => res.json({ ok: true, requests: engine.getRequests(req.query) })));
router.get('/requests/:id', ah(async (req, res) => { const r = engine.getRequest(req.params.id); if (!r) return res.status(404).json({ ok: false, error: 'not found' }); res.json({ ok: true, request: r }); }));
router.get('/chains', ah(async (req, res) => res.json({ ok: true, chains: engine.getChains() })));
router.get('/audit', ah(async (req, res) => res.json({ ok: true, log: engine.getAuditLog(req.query.requestId) })));
router.use((err, req, res, next) => res.status(500).json({ ok: false, error: err.message }));
module.exports = router;
