'use strict';
const express = require('express');
const router = express.Router();
const verifyShopifySession = require('../../middleware/verifyShopifySession');
const { requireCreditsOnMutation } = require('../../core/creditMiddleware');
const ah = fn => (req, res, next) => Promise.resolve(fn(req, res, next)).catch(next);
router.use(verifyShopifySession);
router.get('/health', ah(async (req, res) => res.json({ ok: true, service: 'workflow-orchestrator', v: '2.0.0' })));
const engine = require('./engines/workflow-orchestrator-engine');
router.get('/dashboard', ah(async (req, res) => res.json({ ok: true, ...engine.getStats() })));
router.get('/pipelines', ah(async (req, res) => res.json({ ok: true, pipelines: engine.getPipelines(req.query) })));
router.get('/pipelines/:id', ah(async (req, res) => { const p = engine.getPipeline(req.params.id); if (!p) return res.status(404).json({ ok: false, error: 'not found' }); res.json({ ok: true, pipeline: p }); }));
router.get('/pipelines/:id/tasks', ah(async (req, res) => res.json({ ok: true, tasks: engine.getTasks(req.params.id) })));
router.get('/retry-policies', ah(async (req, res) => res.json({ ok: true, policies: engine.getRetryPolicies() })));
router.use((err, req, res, next) => res.status(500).json({ ok: false, error: err.message }));
module.exports = router;
