'use strict';
const express = require('express');
const router = express.Router();
const verifyShopifySession = require('../../middleware/verifyShopifySession');
const { requireCreditsOnMutation } = require('../../core/creditMiddleware');
const ah = fn => (req, res, next) => Promise.resolve(fn(req, res, next)).catch(next);
router.use(verifyShopifySession);
const engine = require('./engines/workflow-orchestrator-engine');
router.get('/health', ah(async (req, res) => res.json({ ok: true, service: 'workflow-orchestrator', v: '2.0.0' })));
router.get('/stats', ah(async (req, res) => res.json({ ok: true, ...engine.getStats() })));
router.get('/retry-policies', ah(async (req, res) => res.json({ ok: true, ...engine.getRetryPolicies() })));
router.get('/tasks', ah(async (req, res) => res.json({ ok: true, ...engine.getTasks(req.query) })));
router.get('/pipelines', ah(async (req, res) => res.json({ ok: true, ...engine.getPipelines(req.query) })));
router.get('/pipelines/:id', ah(async (req, res) => { const item = engine.getPipeline(req.params.id); if (!item) return res.status(404).json({ ok: false, error: 'not found' }); res.json({ ok: true, pipeline: item }); }));
router.post('/pipelines/:id/retry', ah(async (req, res) => res.json({ ok: true, ...engine.retryPipeline(req.params.id, req.body) })));
router.post('/pipelines/sort', ah(async (req, res) => res.json({ ok: true, sorted: engine.topologicalSort(req.body.dag) })));
router.use((err, req, res, next) => res.status(500).json({ ok: false, error: err.message }));
module.exports = router;
