"use strict";
const express = require("express");
const router = express.Router();
const verifyShopifySession = require("../../middleware/verifyShopifySession");
const engine = require("./engines/workflow-orchestrator-engine");
router.use(verifyShopifySession);
const ah = fn => (req, res, next) => Promise.resolve(fn(req, res, next)).catch(next);
router.get("/health", ah(async (req, res) => res.json({ ok: true, service: "workflow-orchestrator", v: "2.0.0" })));
router.get("/dashboard", ah(async (req, res) => res.json({ ok: true, ...engine.getStats() })));
router.get("/pipelines", ah(async (req, res) => res.json({ ok: true, pipelines: engine.getPipelines(req.query) })));
router.get("/pipelines/:id", ah(async (req, res) => { const p=engine.getPipeline(req.params.id); if(!p) return res.status(404).json({ok:false,error:"not found"}); res.json({ok:true,pipeline:p}); }));
router.get("/pipelines/:id/tasks", ah(async (req, res) => { const tasks=engine.getTasks(req.params.id); res.json({ok:true,tasks,sorted:engine.topologicalSort(tasks)}); }));
router.get("/retry-policies", ah(async (req, res) => res.json({ ok: true, policies: engine.getRetryPolicies() })));
router.post("/pipelines/:id/retry", ah(async (req, res) => res.json({ ok: true, ...engine.retryPipeline(req.params.id) })));
router.post("/pipelines/:id/pause", ah(async (req, res) => res.json({ ok: true, pipelineId: req.params.id, status: "paused" })));
router.post("/pipelines/:id/resume", ah(async (req, res) => res.json({ ok: true, pipelineId: req.params.id, status: "running" })));
router.post("/pipelines", ah(async (req, res) => { if(!req.body.name) return res.status(400).json({ok:false,error:"name required"}); res.json({ok:true,pipeline:{id:"pl_"+Date.now(),...req.body,status:"draft",createdAt:new Date().toISOString()}}); }));
router.use((err, req, res, next) => res.status(500).json({ ok: false, error: err.message }));
module.exports = router;
