'use strict';
const express = require('express');
const router = express.Router();
const verifyShopifySession = require('../../middleware/verifyShopifySession');
const { requireCreditsOnMutation } = require('../../core/creditMiddleware');
const ah = fn => (req, res, next) => Promise.resolve(fn(req, res, next)).catch(next);
router.use(verifyShopifySession);
router.get('/health', ah(async (req, res) => res.json({ ok: true, service: 'conversion-rate-optimization', v: '2.0.0' })));
const engine = require('./engines/cro-engine');
router.get('/dashboard', ah(async (req, res) => res.json({ ok: true, ...engine.getDashboardStats() })));
router.get('/experiments', ah(async (req, res) => res.json({ ok: true, experiments: engine.getExperiments(req.query) })));
router.get('/experiments/:id', ah(async (req, res) => { const e = engine.getExperiment(req.params.id); if (!e) return res.status(404).json({ ok: false, error: 'not found' }); res.json({ ok: true, experiment: e }); }));
router.get('/heatmaps', ah(async (req, res) => res.json({ ok: true, heatmaps: engine.getHeatmaps() })));
router.post('/scan', requireCreditsOnMutation('cro-scan'), ah(async (req, res) => { const { url } = req.body; if (!url) return res.status(400).json({ ok: false, error: 'url required' }); res.json({ ok: true, ...engine.runCroScan(url) }); }));
router.use((err, req, res, next) => res.status(500).json({ ok: false, error: err.message }));
module.exports = router;
