'use strict';
const express = require('express');
const router = express.Router();
const verifyShopifySession = require('../../middleware/verifyShopifySession');
const { requireCreditsOnMutation } = require('../../core/creditMiddleware');
const ah = fn => (req, res, next) => Promise.resolve(fn(req, res, next)).catch(next);
router.use(verifyShopifySession);
const engine = require('./engines/cro-engine');
router.get('/health', ah(async (req, res) => res.json({ ok: true, service: 'conversion-rate-optimization', v: '2.0.0' })));
router.get('/dashboard', ah(async (req, res) => res.json({ ok: true, ...engine.getDashboardStats() })));
router.get('/insights', ah(async (req, res) => res.json({ ok: true, ...engine.getInsights() })));
router.get('/funnel', ah(async (req, res) => res.json({ ok: true, ...engine.getFunnel(req.query) })));
router.get('/heatmaps', ah(async (req, res) => res.json({ ok: true, ...engine.getHeatmaps() })));
router.get('/ab-tests', ah(async (req, res) => res.json({ ok: true, ...engine.getAbTests(req.query) })));
router.get('/ab-tests/:id', ah(async (req, res) => { const item = engine.getAbTest(req.params.id); if (!item) return res.status(404).json({ ok: false, error: 'not found' }); res.json({ ok: true, test: item }); }));
router.use((err, req, res, next) => res.status(500).json({ ok: false, error: err.message }));
module.exports = router;
