'use strict';
const express = require('express');
const router = express.Router();
const verifyShopifySession = require('../../middleware/verifyShopifySession');
const { requireCreditsOnMutation } = require('../../core/creditMiddleware');
const ah = fn => (req, res, next) => Promise.resolve(fn(req, res, next)).catch(next);
router.use(verifyShopifySession);
const engine = require('./engines/auto-insights-engine');
router.get('/health', ah(async (req, res) => res.json({ ok: true, service: 'auto-insights', v: '2.0.0' })));
router.get('/dashboard', ah(async (req, res) => res.json({ ok: true, ...engine.getDashboardStats() })));
router.get('/insights', ah(async (req, res) => res.json({ ok: true, ...engine.getInsights(req.query) })));
router.get('/insights/:id', ah(async (req, res) => { const item = engine.getInsight(req.params.id); if (!item) return res.status(404).json({ ok: false, error: 'not found' }); res.json({ ok: true, insight: item }); }));
router.post('/insights/generate', requireCreditsOnMutation('content-brief'), ah(async (req, res) => res.json({ ok: true, ...engine.generateInsight(req.body) })));
router.use((err, req, res, next) => res.status(500).json({ ok: false, error: err.message }));
module.exports = router;
