'use strict';
const express = require('express');
const router = express.Router();
const verifyShopifySession = require('../../middleware/verifyShopifySession');
const { requireCreditsOnMutation } = require('../../core/creditMiddleware');
const engine = require('./engines/auto-insights-engine');
const ah = fn => (req, res, next) => Promise.resolve(fn(req, res, next)).catch(next);
router.use(verifyShopifySession);
router.get('/health', ah(async (req, res) => res.json({ ok: true, service: 'auto-insights', v: '2.0.0' })));
router.get('/dashboard', ah(async (req, res) => res.json({ ok: true, ...engine.getDashboardStats() })));
router.get('/insights', ah(async (req, res) => res.json({ ok: true, insights: engine.getInsights(req.query) })));
router.get('/insights/:id', ah(async (req, res) => { const i = engine.getInsight(req.params.id); if (!i) return res.status(404).json({ ok: false, error: 'not found' }); res.json({ ok: true, insight: i }); }));
router.post('/generate', requireCreditsOnMutation('analytics-insight'), ah(async (req, res) => { const { metric, data } = req.body; if (!metric) return res.status(400).json({ ok: false, error: 'metric required' }); res.json({ ok: true, ...engine.generateInsight(metric, data || {}) }); }));
router.use((err, req, res, next) => res.status(500).json({ ok: false, error: err.message }));
module.exports = router;
