services:
  - type: web
    name: aura-core-monolith
    runtime: node
    autoDeploy: true
    branch: main
    buildCommand: npm install && npm run build:console
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
