'use strict';
const express = require('express');
const router = express.Router();
const verifyShopifySession = require('../../middleware/verifyShopifySession');
const engine = require('./engines/brand-mention-engine');
router.use(verifyShopifySession);
const ah = fn => (req, res, next) => Promise.resolve(fn(req, res, next)).catch(next);
router.get('/health', ah(async (req, res) => res.json({ ok: true, service: 'brand-mention-tracker', v: '2.0.0' })));
router.get('/dashboard', ah(async (req, res) => res.json({ ok: true, ...engine.getDashboardStats() })));
router.get('/mentions', ah(async (req, res) => res.json({ ok: true, mentions: engine.getMentions(req.query) })));
router.get('/mentions/:id', ah(async (req, res) => { const m = engine.getMention(req.params.id); if (!m) return res.status(404).json({ ok: false, error: 'not found' }); res.json({ ok: true, mention: m }); }));
router.get('/alerts', ah(async (req, res) => res.json({ ok: true, alerts: engine.getAlerts() })));
router.get('/sentiment-trend', ah(async (req, res) => res.json({ ok: true, trend: engine.getSentimentTrend() })));
router.get('/sources', ah(async (req, res) => res.json({ ok: true, sources: engine.getSources() })));
router.use((err, req, res, next) => res.status(500).json({ ok: false, error: err.message }));
module.exports = router;
