'use strict';
const express = require('express');
const router = express.Router();
const verifyShopifySession = require('../../middleware/verifyShopifySession');
const { requireCreditsOnMutation } = require('../../core/creditMiddleware');
const engine = require('./engines/predictive-analytics-engine');
router.use(verifyShopifySession);
const ah = fn => (req, res, next) => Promise.resolve(fn(req, res, next)).catch(next);
router.get('/health', ah(async (req, res) => res.json({ ok: true, service: 'predictive-analytics-widgets', v: '2.0.0' })));
router.get('/dashboard', ah(async (req, res) => res.json({ ok: true, ...engine.getDashboardStats() })));
router.get('/widgets', ah(async (req, res) => res.json({ ok: true, widgets: engine.getWidgets(req.query) })));
router.get('/widgets/:id', ah(async (req, res) => { const w = engine.getWidget(req.params.id); if (!w) return res.status(404).json({ ok: false, error: 'not found' }); res.json({ ok: true, widget: w }); }));
router.get('/catalog', ah(async (req, res) => res.json({ ok: true, catalog: engine.getWidgetCatalog() })));
router.post('/forecast', requireCreditsOnMutation('analytics-insight'), ah(async (req, res) => { if (!req.body.metric) return res.status(400).json({ ok: false, error: 'metric required' }); res.json({ ok: true, ...engine.runForecast(req.body.metric, req.body.horizon || 90) }); }));
router.use((err, req, res, next) => res.status(500).json({ ok: false, error: err.message }));
module.exports = router;
