'use strict';
const express = require('express');
const router = express.Router();
const verifyShopifySession = require('../../middleware/verifyShopifySession');
const { requireCreditsOnMutation } = require('../../core/creditMiddleware');
const ah = fn => (req, res, next) => Promise.resolve(fn(req, res, next)).catch(next);
router.use(verifyShopifySession);
const engine = require('./engines/predictive-analytics-engine');
router.get('/health', ah(async (req, res) => res.json({ ok: true, service: 'predictive-analytics-widgets', v: '2.0.0' })));
router.get('/dashboard', ah(async (req, res) => res.json({ ok: true, ...engine.getDashboardStats() })));
router.get('/widget-catalog', ah(async (req, res) => res.json({ ok: true, ...engine.getWidgetCatalog() })));
router.get('/widgets', ah(async (req, res) => res.json({ ok: true, ...engine.getWidgets(req.query) })));
router.get('/widgets/:id', ah(async (req, res) => { const item = engine.getWidget(req.params.id); if (!item) return res.status(404).json({ ok: false, error: 'not found' }); res.json({ ok: true, widget: item }); }));
router.post('/forecast/run', requireCreditsOnMutation('seo-scan'), ah(async (req, res) => res.json({ ok: true, ...engine.runForecast(req.body) })));
router.use((err, req, res, next) => res.status(500).json({ ok: false, error: err.message }));
module.exports = router;
