'use strict';
const express = require('express');
const router = express.Router();
const verifyShopifySession = require('../../middleware/verifyShopifySession');
const { requireCreditsOnMutation } = require('../../core/creditMiddleware');
const ah = fn => (req, res, next) => Promise.resolve(fn(req, res, next)).catch(next);
router.use(verifyShopifySession);
router.get('/health', ah(async (req, res) => res.json({ ok: true, service: 'landing-page-builder', v: '2.0.0' })));
const engine = require('./engines/landing-page-engine');
router.get('/dashboard', ah(async (req, res) => res.json({ ok: true, ...engine.getDashboardStats() })));
router.get('/pages', ah(async (req, res) => res.json({ ok: true, pages: engine.getPages(req.query) })));
router.get('/pages/:id', ah(async (req, res) => { const p = engine.getPage(req.params.id); if (!p) return res.status(404).json({ ok: false, error: 'not found' }); res.json({ ok: true, page: p }); }));
router.get('/templates', ah(async (req, res) => res.json({ ok: true, templates: engine.getTemplates() })));
router.get('/blocks', ah(async (req, res) => res.json({ ok: true, blocks: engine.getBlocks() })));
router.post('/generate-copy', requireCreditsOnMutation('page-generate'), ah(async (req, res) => { const { templateId, productName, keywords = [] } = req.body; if (!templateId || !productName) return res.status(400).json({ ok: false, error: 'templateId and productName required' }); res.json({ ok: true, ...engine.generateCopy(templateId, productName, keywords) }); }));
router.use((err, req, res, next) => res.status(500).json({ ok: false, error: err.message }));
module.exports = router;
