'use strict';
const express = require('express');
const router = express.Router();
const verifyShopifySession = require('../../middleware/verifyShopifySession');
const { requireCreditsOnMutation } = require('../../core/creditMiddleware');
const ah = fn => (req, res, next) => Promise.resolve(fn(req, res, next)).catch(next);
router.use(verifyShopifySession);
const engine = require('./engines/landing-page-engine');
router.get('/health', ah(async (req, res) => res.json({ ok: true, service: 'landing-page-builder', v: '2.0.0' })));
router.get('/dashboard', ah(async (req, res) => res.json({ ok: true, ...engine.getDashboardStats() })));
router.get('/blocks', ah(async (req, res) => res.json({ ok: true, ...engine.getBlocks(req.query) })));
router.get('/templates', ah(async (req, res) => res.json({ ok: true, ...engine.getTemplates(req.query) })));
router.get('/pages', ah(async (req, res) => res.json({ ok: true, ...engine.getPages(req.query) })));
router.get('/pages/:id', ah(async (req, res) => { const item = engine.getPage(req.params.id); if (!item) return res.status(404).json({ ok: false, error: 'not found' }); res.json({ ok: true, page: item }); }));
router.post('/copy/generate', requireCreditsOnMutation('content-brief'), ah(async (req, res) => res.json({ ok: true, ...engine.generateCopy(req.body) })));
router.use((err, req, res, next) => res.status(500).json({ ok: false, error: err.message }));
module.exports = router;
