'use strict';
const express = require('express');
const router = express.Router();
const verifyShopifySession = require('../../middleware/verifyShopifySession');
const { requireCreditsOnMutation } = require('../../core/creditMiddleware');
const ah = fn => (req, res, next) => Promise.resolve(fn(req, res, next)).catch(next);
router.use(verifyShopifySession);
const engine = require('./engines/visual-workflow-engine');
router.get('/health', ah(async (req, res) => res.json({ ok: true, service: 'visual-workflow-builder', v: '2.0.0' })));
router.get('/dashboard', ah(async (req, res) => res.json({ ok: true, ...engine.getDashboardStats() })));
router.get('/node-types', ah(async (req, res) => res.json({ ok: true, nodeTypes: engine.getNodeTypes() })));
router.get('/trigger-types', ah(async (req, res) => res.json({ ok: true, triggerTypes: engine.getTriggerTypes() })));
router.get('/executions', ah(async (req, res) => res.json({ ok: true, ...engine.getExecutions(req.query) })));
router.get('/workflows', ah(async (req, res) => res.json({ ok: true, ...engine.getWorkflows(req.query) })));
router.get('/workflows/:id', ah(async (req, res) => { const item = engine.getWorkflow(req.params.id); if (!item) return res.status(404).json({ ok: false, error: 'not found' }); res.json({ ok: true, workflow: item }); }));
router.post('/workflows/validate', ah(async (req, res) => res.json({ ok: true, ...engine.validateDag(req.body.dag) })));
router.post('/workflows/from-nl', requireCreditsOnMutation('content-brief'), ah(async (req, res) => { if (!req.body.description) return res.status(400).json({ ok: false, error: 'description required' }); res.json({ ok: true, ...engine.nlToWorkflow(req.body.description) }); }));
router.use((err, req, res, next) => res.status(500).json({ ok: false, error: err.message }));
module.exports = router;
