'use strict';
const express = require('express');
const router = express.Router();
const verifyShopifySession = require('../../middleware/verifyShopifySession');
const { requireCreditsOnMutation } = require('../../core/creditMiddleware');
const ah = fn => (req, res, next) => Promise.resolve(fn(req, res, next)).catch(next);
router.use(verifyShopifySession);
router.get('/health', ah(async (req, res) => res.json({ ok: true, service: 'visual-workflow-builder', v: '2.0.0' })));
const engine = require('./engines/visual-workflow-engine');
router.get('/dashboard', ah(async (req, res) => res.json({ ok: true, ...engine.getDashboardStats() })));
router.get('/workflows', ah(async (req, res) => res.json({ ok: true, workflows: engine.getWorkflows(req.query) })));
router.get('/workflows/:id', ah(async (req, res) => { const w = engine.getWorkflow(req.params.id); if (!w) return res.status(404).json({ ok: false, error: 'not found' }); res.json({ ok: true, workflow: w }); }));
router.get('/workflows/:id/executions', ah(async (req, res) => res.json({ ok: true, executions: engine.getExecutions(req.params.id) })));
router.get('/node-types', ah(async (req, res) => res.json({ ok: true, nodeTypes: engine.getNodeTypes() })));
router.get('/trigger-types', ah(async (req, res) => res.json({ ok: true, triggerTypes: engine.getTriggerTypes() })));
router.post('/validate', ah(async (req, res) => { const { nodes = [], edges = [] } = req.body; res.json({ ok: true, ...engine.validateDag(nodes, edges) }); }));
router.use((err, req, res, next) => res.status(500).json({ ok: false, error: err.message }));
module.exports = router;
