'use strict';
const express = require('express');
const router = express.Router();
const verifyShopifySession = require('../../middleware/verifyShopifySession');
const engine = require('./engines/returns-engine');
router.use(verifyShopifySession);
const ah = fn => (req, res, next) => Promise.resolve(fn(req, res, next)).catch(next);
router.get('/health', ah(async (req, res) => res.json({ ok: true, service: 'returns-rma-automation', v: '2.0.0' })));
router.get('/dashboard', ah(async (req, res) => res.json({ ok: true, ...(engine.getDashboardStats ? engine.getDashboardStats() : {}) })));
router.get('/returns', ah(async (req, res) => res.json({ ok: true, ...(engine.getReturns ? engine.getReturns(req.query) : {}) })));
router.get('/returns/:id', ah(async (req, res) => res.json({ ok: true, ...(engine.getReturn ? engine.getReturn(req.params.id) : {}) })));
router.post('/returns/:id/approve', ah(async (req, res) => res.json({ ok: true, returnId: req.params.id, status: 'approved', approvedAt: new Date().toISOString() })));
router.post('/returns/:id/reject', ah(async (req, res) => res.json({ ok: true, returnId: req.params.id, status: 'rejected', rejectedAt: new Date().toISOString(), reason: req.body.reason })));
router.get('/fraud-flags', ah(async (req, res) => res.json({ ok: true, ...(engine.getFraudFlags ? engine.getFraudFlags() : {}) })));
router.use((err, req, res, next) => res.status(500).json({ ok: false, error: err.message }));
module.exports = router;
