'use strict';
const express = require('express');
const router = express.Router();
const verifyShopifySession = require('../../middleware/verifyShopifySession');
const { requireCreditsOnMutation } = require('../../core/creditMiddleware');
const ah = fn => (req, res, next) => Promise.resolve(fn(req, res, next)).catch(next);
router.use(verifyShopifySession);
const engine = require('./engines/aura-api-sdk-engine');
router.get('/health', ah(async (req, res) => res.json({ ok: true, service: 'aura-api-sdk', v: '2.0.0' })));
router.get('/dashboard', ah(async (req, res) => res.json({ ok: true, ...engine.getDashboardStats() })));
router.get('/sdk-languages', ah(async (req, res) => res.json({ ok: true, languages: engine.getSdkLanguages() })));
router.get('/usage-history', ah(async (req, res) => res.json({ ok: true, ...engine.getUsageHistory(req.query) })));
router.get('/endpoints', ah(async (req, res) => res.json({ ok: true, ...engine.getEndpoints(req.query) })));
router.get('/keys', ah(async (req, res) => res.json({ ok: true, ...engine.getApiKeys(req.query) })));
router.get('/keys/:id', ah(async (req, res) => { const item = engine.getApiKey(req.params.id); if (!item) return res.status(404).json({ ok: false, error: 'not found' }); res.json({ ok: true, key: item }); }));
router.post('/keys', ah(async (req, res) => res.json({ ok: true, ...engine.createApiKey(req.body) })));
router.delete('/keys/:id', ah(async (req, res) => res.json({ ok: true, ...engine.revokeApiKey(req.params.id) })));
router.post('/keys/test', ah(async (req, res) => res.json({ ok: true, ...engine.testApiKey(req.body) })));
router.post('/code-snippet', ah(async (req, res) => res.json({ ok: true, ...engine.generateCodeSnippet(req.body) })));
router.use((err, req, res, next) => res.status(500).json({ ok: false, error: err.message }));
module.exports = router;
