'use strict';
const express = require('express');
const router = express.Router();
const verifyShopifySession = require('../../middleware/verifyShopifySession');
const engine = require('./engines/mobile-app-engine');
router.use(verifyShopifySession);
const ah = fn => (req, res, next) => Promise.resolve(fn(req, res, next)).catch(next);
router.get('/health', ah(async (req, res) => res.json({ ok: true, service: 'mobile-app-analytics', v: '2.0.0' })));
router.get('/dashboard', ah(async (req, res) => res.json({ ok: true, ...engine.getDashboardStats() })));
router.get('/metrics', ah(async (req, res) => res.json({ ok: true, metrics: engine.getAppMetrics() })));
router.get('/screens', ah(async (req, res) => res.json({ ok: true, screens: engine.getScreens() })));
router.get('/events', ah(async (req, res) => res.json({ ok: true, events: engine.getEvents() })));
router.get('/push-campaigns', ah(async (req, res) => res.json({ ok: true, campaigns: engine.getPushCampaigns() })));
router.use((err, req, res, next) => res.status(500).json({ ok: false, error: err.message }));
module.exports = router;
