'use strict';
const express = require('express');
const router = express.Router();
const verifyShopifySession = require('../../middleware/verifyShopifySession');
const { requireCreditsOnMutation } = require('../../core/creditMiddleware');
const ah = fn => (req, res, next) => Promise.resolve(fn(req, res, next)).catch(next);
router.use(verifyShopifySession);
const engine = require('./engines/voice-search-engine');
router.get('/health', ah(async (req, res) => res.json({ ok: true, service: 'voice-search-optimization', v: '2.0.0' })));
router.get('/dashboard', ah(async (req, res) => res.json({ ok: true, ...engine.getDashboardStats() })));
router.get('/faq-schema', ah(async (req, res) => res.json({ ok: true, ...engine.getFaqSchema(req.query) })));
router.get('/conversational-keywords', ah(async (req, res) => res.json({ ok: true, ...engine.getConversationalKeywords(req.query) })));
router.get('/voice-queries', ah(async (req, res) => res.json({ ok: true, ...engine.getVoiceQueries(req.query) })));
router.post('/faq/generate-answer', requireCreditsOnMutation('email-gen'), ah(async (req, res) => res.json({ ok: true, ...engine.generateFaqAnswer(req.body) })));
router.use((err, req, res, next) => res.status(500).json({ ok: false, error: err.message }));
module.exports = router;
