'use strict';
const express = require('express');
const router = express.Router();
const verifyShopifySession = require('../../middleware/verifyShopifySession');
const { requireCreditsOnMutation } = require('../../core/creditMiddleware');
const ah = fn => (req, res, next) => Promise.resolve(fn(req, res, next)).catch(next);
router.use(verifyShopifySession);
router.get('/health', ah(async (req, res) => res.json({ ok: true, service: 'voice-search-optimization', v: '2.0.0' })));
const engine = require('./engines/voice-search-engine');
router.get('/dashboard', ah(async (req, res) => res.json({ ok: true, ...engine.getDashboardStats() })));
router.get('/queries', ah(async (req, res) => res.json({ ok: true, queries: engine.getVoiceQueries() })));
router.get('/keywords', ah(async (req, res) => res.json({ ok: true, keywords: engine.getConversationalKeywords() })));
router.get('/faq-schema', ah(async (req, res) => res.json({ ok: true, schema: engine.getFaqSchema() })));
router.post('/generate-faq', requireCreditsOnMutation('voice-answer'), ah(async (req, res) => { const { question } = req.body; if (!question) return res.status(400).json({ ok: false, error: 'question required' }); res.json({ ok: true, ...engine.generateFaqAnswer(question) }); }));
router.use((err, req, res, next) => res.status(500).json({ ok: false, error: err.message }));
module.exports = router;
