'use strict';
const express = require('express');
const router = express.Router();
const verifyShopifySession = require('../../middleware/verifyShopifySession');
const { requireCreditsOnMutation } = require('../../core/creditMiddleware');
const ah = fn => (req, res, next) => Promise.resolve(fn(req, res, next)).catch(next);
router.use(verifyShopifySession);
router.get('/health', ah(async (req, res) => res.json({ ok: true, service: 'inbox-assistant', v: '2.0.0' })));
const engine = require('./engines/inbox-engine');
router.get('/dashboard', ah(async (req, res) => res.json({ ok: true, ...engine.getDashboardStats() })));
router.get('/conversations', ah(async (req, res) => res.json({ ok: true, conversations: engine.getConversations(req.query) })));
router.get('/conversations/:id', ah(async (req, res) => { const c = engine.getConversation(req.params.id); if (!c) return res.status(404).json({ ok: false, error: 'not found' }); res.json({ ok: true, conversation: c }); }));
router.get('/canned-responses', ah(async (req, res) => res.json({ ok: true, responses: engine.getCannedResponses() })));
router.use((err, req, res, next) => res.status(500).json({ ok: false, error: err.message }));
module.exports = router;
