'use strict';
const express = require('express');
const router = express.Router();
const verifyShopifySession = require('../../middleware/verifyShopifySession');
const { requireCreditsOnMutation } = require('../../core/creditMiddleware');
const engine = require('./engines/ai-segmentation-engine');
router.use(verifyShopifySession);
const ah = fn => (req, res, next) => Promise.resolve(fn(req, res, next)).catch(next);
router.get('/health', ah(async (req, res) => res.json({ ok: true, service: 'ai-segmentation-engine', v: '2.0.0' })));
router.get('/dashboard', ah(async (req, res) => res.json({ ok: true, ...engine.getDashboardStats() })));
router.get('/segments', ah(async (req, res) => res.json({ ok: true, segments: engine.getSegments(req.query) })));
router.get('/segments/:id', ah(async (req, res) => { const s = engine.getSegment(req.params.id); if (!s) return res.status(404).json({ ok: false, error: 'not found' }); res.json({ ok: true, segment: s }); }));
router.get('/segments/:id/insights', ah(async (req, res) => res.json({ ok: true, ...engine.getSegmentInsights(req.params.id) })));
router.get('/attributes', ah(async (req, res) => res.json({ ok: true, attributes: engine.getAttributes() })));
router.post('/segments/build', requireCreditsOnMutation('analytics-insight'), ah(async (req, res) => { const { name, rules } = req.body; if (!name || !rules) return res.status(400).json({ ok: false, error: 'name and rules required' }); res.json({ ok: true, ...engine.buildSegment(name, rules) }); }));
router.use((err, req, res, next) => res.status(500).json({ ok: false, error: err.message }));
module.exports = router;
