'use strict';
const express = require('express');
const router = express.Router();
const verifyShopifySession = require('../../middleware/verifyShopifySession');
const { requireCreditsOnMutation } = require('../../core/creditMiddleware');
const ah = fn => (req, res, next) => Promise.resolve(fn(req, res, next)).catch(next);
router.use(verifyShopifySession);
const engine = require('./engines/ai-segmentation-engine');
router.get('/health', ah(async (req, res) => res.json({ ok: true, service: 'ai-segmentation-engine', v: '2.0.0' })));
router.get('/dashboard', ah(async (req, res) => res.json({ ok: true, ...engine.getDashboardStats() })));
router.get('/attributes', ah(async (req, res) => res.json({ ok: true, ...engine.getAttributes() })));
router.get('/segments', ah(async (req, res) => res.json({ ok: true, ...engine.getSegments(req.query) })));
router.get('/segments/:id', ah(async (req, res) => { const item = engine.getSegment(req.params.id); if (!item) return res.status(404).json({ ok: false, error: 'not found' }); res.json({ ok: true, segment: item }); }));
router.get('/segments/:id/insights', ah(async (req, res) => res.json({ ok: true, ...engine.getSegmentInsights(req.params.id) })));
router.post('/segments/build', requireCreditsOnMutation('content-brief'), ah(async (req, res) => res.json({ ok: true, ...engine.buildSegment(req.body) })));
router.use((err, req, res, next) => res.status(500).json({ ok: false, error: err.message }));
module.exports = router;
