'use strict';
const express = require('express');
const router = express.Router();
const verifyShopifySession = require('../../middleware/verifyShopifySession');
const engine = require('./engines/supplier-sync-engine');
router.use(verifyShopifySession);
const ah = fn => (req, res, next) => Promise.resolve(fn(req, res, next)).catch(next);
router.get('/health', ah(async (req, res) => res.json({ ok: true, service: 'inventory-supplier-sync', v: '2.0.0' })));
router.get('/dashboard', ah(async (req, res) => res.json({ ok: true, ...(engine.getDashboardStats ? engine.getDashboardStats() : {}) })));
router.get('/suppliers', ah(async (req, res) => res.json({ ok: true, ...(engine.getSuppliers ? engine.getSuppliers() : {}) })));
router.get('/inventory', ah(async (req, res) => res.json({ ok: true, ...(engine.getInventory ? engine.getInventory() : {}) })));
router.get('/purchase-orders', ah(async (req, res) => res.json({ ok: true, ...(engine.getPurchaseOrders ? engine.getPurchaseOrders() : {}) })));
router.post('/sync', ah(async (req, res) => res.json({ ok: true, status: 'synced', syncedAt: new Date().toISOString() })));
router.use((err, req, res, next) => res.status(500).json({ ok: false, error: err.message }));
module.exports = router;
