'use strict';
const express = require('express');
const router = express.Router();
const verifyShopifySession = require('../../middleware/verifyShopifySession');
const { requireCreditsOnMutation } = require('../../core/creditMiddleware');
const engine = require('./engines/supplier-sync-engine');
const ah = fn => (req, res, next) => Promise.resolve(fn(req, res, next)).catch(next);
router.use(verifyShopifySession);
router.get('/health', ah(async (req, res) => res.json({ ok: true, service: 'inventory-supplier-sync', v: '2.0.0' })));
router.get('/dashboard', ah(async (req, res) => res.json({ ok: true, ...engine.getDashboardStats() })));
router.get('/suppliers', ah(async (req, res) => res.json({ ok: true, suppliers: engine.getSuppliers(req.query) })));
router.get('/suppliers/:id', ah(async (req, res) => { const s = engine.getSupplier(req.params.id); if (!s) return res.status(404).json({ ok: false, error: 'not found' }); res.json({ ok: true, supplier: s }); }));
router.get('/alerts', ah(async (req, res) => res.json({ ok: true, alerts: engine.getDisruptionAlerts() })));
router.get('/benchmarks', ah(async (req, res) => res.json({ ok: true, benchmarks: engine.getBenchmarks() })));
router.get('/carbon', ah(async (req, res) => res.json({ ok: true, carbon: engine.getCarbonFootprint() })));
router.post('/lead-time', ah(async (req, res) => { const { supplierId } = req.body; if (!supplierId) return res.status(400).json({ ok: false, error: 'supplierId required' }); res.json({ ok: true, ...engine.getLeadTimeDistribution(supplierId) }); }));
router.post('/alternatives', ah(async (req, res) => { const { category } = req.body; if (!category) return res.status(400).json({ ok: false, error: 'category required' }); res.json({ ok: true, alternatives: engine.getAlternativeSuppliers(category) }); }));
router.use((err, req, res, next) => res.status(500).json({ ok: false, error: err.message }));
module.exports = router;
