'use strict';
const express = require('express');
const router = express.Router();
const verifyShopifySession = require('../../middleware/verifyShopifySession');
const { requireCreditsOnMutation } = require('../../core/creditMiddleware');
const ah = fn => (req, res, next) => Promise.resolve(fn(req, res, next)).catch(next);
router.use(verifyShopifySession);
const engine = require('./engines/omnichannel-engine');
router.get('/health', ah(async (req, res) => res.json({ ok: true, service: 'omnichannel-campaign-builder', v: '2.0.0' })));
router.get('/dashboard', ah(async (req, res) => res.json({ ok: true, ...engine.getDashboardStats() })));
router.get('/channels', ah(async (req, res) => res.json({ ok: true, ...engine.getChannelCatalog() })));
router.get('/journey-template', ah(async (req, res) => res.json({ ok: true, ...engine.getJourneyTemplate() })));
router.get('/campaigns', ah(async (req, res) => res.json({ ok: true, ...engine.getCampaigns(req.query) })));
router.get('/campaigns/:id', ah(async (req, res) => { const item = engine.getCampaign(req.params.id); if (!item) return res.status(404).json({ ok: false, error: 'not found' }); res.json({ ok: true, campaign: item }); }));
router.post('/campaigns/brief', requireCreditsOnMutation('content-brief'), ah(async (req, res) => res.json({ ok: true, ...engine.generateBrief(req.body) })));
router.use((err, req, res, next) => res.status(500).json({ ok: false, error: err.message }));
module.exports = router;
