'use strict';
const express = require('express');
const router = express.Router();
const verifyShopifySession = require('../../middleware/verifyShopifySession');
const { requireCreditsOnMutation } = require('../../core/creditMiddleware');
const ah = fn => (req, res, next) => Promise.resolve(fn(req, res, next)).catch(next);
router.use(verifyShopifySession);
router.get('/health', ah(async (req, res) => res.json({ ok: true, service: 'newsletter-automation', v: '2.0.0' })));
const engine = require('./engines/newsletter-engine');
router.get('/dashboard', ah(async (req, res) => res.json({ ok: true, ...engine.getDashboardStats() })));
router.get('/newsletters', ah(async (req, res) => res.json({ ok: true, newsletters: engine.getNewsletters(req.query) })));
router.get('/newsletters/:id', ah(async (req, res) => { const n = engine.getNewsletter(req.params.id); if (!n) return res.status(404).json({ ok: false, error: 'not found' }); res.json({ ok: true, newsletter: n }); }));
router.get('/subscribers', ah(async (req, res) => res.json({ ok: true, ...engine.getSubscriberStats() })));
router.get('/segments', ah(async (req, res) => res.json({ ok: true, segments: engine.getSegments() })));
router.post('/subject-lines', requireCreditsOnMutation('newsletter-generate'), ah(async (req, res) => { const { topic, count = 5 } = req.body; if (!topic) return res.status(400).json({ ok: false, error: 'topic required' }); res.json({ ok: true, subjectLines: engine.generateSubjectLines(topic, count) }); }));
router.use((err, req, res, next) => res.status(500).json({ ok: false, error: err.message }));
module.exports = router;
