'use strict';
const express = require('express');
const router = express.Router();
const verifyShopifySession = require('../../middleware/verifyShopifySession');
const { requireCreditsOnMutation } = require('../../core/creditMiddleware');
const ah = fn => (req, res, next) => Promise.resolve(fn(req, res, next)).catch(next);
router.use(verifyShopifySession);
const engine = require('./engines/newsletter-engine');
router.get('/health', ah(async (req, res) => res.json({ ok: true, service: 'newsletter-automation', v: '2.0.0' })));
router.get('/dashboard', ah(async (req, res) => res.json({ ok: true, ...engine.getDashboardStats() })));
router.get('/segments', ah(async (req, res) => res.json({ ok: true, ...engine.getSegments(req.query) })));
router.get('/subscriber-stats', ah(async (req, res) => res.json({ ok: true, ...engine.getSubscriberStats(req.query) })));
router.get('/newsletters', ah(async (req, res) => res.json({ ok: true, ...engine.getNewsletters(req.query) })));
router.get('/newsletters/:id', ah(async (req, res) => { const item = engine.getNewsletter(req.params.id); if (!item) return res.status(404).json({ ok: false, error: 'not found' }); res.json({ ok: true, newsletter: item }); }));
router.post('/subject-lines/generate', requireCreditsOnMutation('email-gen'), ah(async (req, res) => res.json({ ok: true, ...engine.generateSubjectLines(req.body) })));
router.use((err, req, res, next) => res.status(500).json({ ok: false, error: err.message }));
module.exports = router;
