'use strict';
const express = require('express');
const router = express.Router();
const verifyShopifySession = require('../../middleware/verifyShopifySession');
const { requireCreditsOnMutation } = require('../../core/creditMiddleware');
const engine = require('./engines/launch-planner-engine');
router.use(verifyShopifySession);
const ah = fn => (req, res, next) => Promise.resolve(fn(req, res, next)).catch(next);
router.get('/health', ah(async (req, res) => res.json({ ok: true, service: 'ai-launch-planner', v: '2.0.0' })));
router.get('/dashboard', ah(async (req, res) => res.json({ ok: true, ...engine.getDashboardStats() })));
router.get('/launches', ah(async (req, res) => res.json({ ok: true, launches: engine.getLaunches(req.query) })));
router.get('/launches/:id', ah(async (req, res) => { const l = engine.getLaunch(req.params.id); if (!l) return res.status(404).json({ ok: false, error: 'not found' }); res.json({ ok: true, launch: l }); }));
router.get('/templates', ah(async (req, res) => res.json({ ok: true, templates: engine.getTemplates() })));
router.post('/generate', requireCreditsOnMutation('campaign-gen'), ah(async (req, res) => { const { name, launchDate } = req.body; if (!name || !launchDate) return res.status(400).json({ ok: false, error: 'name and launchDate required' }); res.json({ ok: true, ...engine.generateLaunchPlan(name, launchDate, req.body.budget || 1000, req.body.channels, req.body.templateId) }); }));
router.post('/launches', ah(async (req, res) => { const { name, launchDate } = req.body; if (!name || !launchDate) return res.status(400).json({ ok: false, error: 'name and launchDate required' }); res.json({ ok: true, launch: { id: 'l_' + Date.now(), ...req.body, status: 'planning', progress: 0, createdAt: new Date().toISOString() } }); }));
router.use((err, req, res, next) => res.status(500).json({ ok: false, error: err.message }));
module.exports = router;
