'use strict';
const express = require('express');
const router = express.Router();
const verifyShopifySession = require('../../middleware/verifyShopifySession');
const { requireCreditsOnMutation } = require('../../core/creditMiddleware');
const ah = fn => (req, res, next) => Promise.resolve(fn(req, res, next)).catch(next);
router.use(verifyShopifySession);
router.get('/health', ah(async (req, res) => res.json({ ok: true, service: 'ai-launch-planner', v: '2.0.0' })));
const engine = require('./engines/launch-planner-engine');
router.get('/dashboard', ah(async (req, res) => res.json({ ok: true, ...engine.getDashboardStats() })));
router.get('/launches', ah(async (req, res) => res.json({ ok: true, launches: engine.getLaunches(req.query) })));
router.get('/launches/:id', ah(async (req, res) => { const l = engine.getLaunch(req.params.id); if (!l) return res.status(404).json({ ok: false, error: 'not found' }); res.json({ ok: true, launch: l }); }));
router.get('/channels', ah(async (req, res) => res.json({ ok: true, channels: engine.getChannels() })));
router.post('/brief', requireCreditsOnMutation('campaign-gen'), ah(async (req, res) => { const { productName, targetAudience } = req.body; if (!productName) return res.status(400).json({ ok: false, error: 'productName required' }); res.json({ ok: true, ...engine.generateLaunchBrief(productName, targetAudience || '') }); }));
router.use((err, req, res, next) => res.status(500).json({ ok: false, error: err.message }));
module.exports = router;
