'use strict';
const express = require('express');
const router = express.Router();
const verifyShopifySession = require('../../middleware/verifyShopifySession');
const { requireCreditsOnMutation } = require('../../core/creditMiddleware');
const engine = require('./engines/ltv-engine');
const ah = fn => (req, res, next) => Promise.resolve(fn(req, res, next)).catch(next);
router.use(verifyShopifySession);
router.get('/health', ah(async (req, res) => res.json({ ok: true, service: 'ltv-churn-predictor', v: '2.0.0' })));
router.get('/dashboard', ah(async (req, res) => res.json({ ok: true, ...engine.getSummary() })));
router.get('/segments', ah(async (req, res) => res.json({ ok: true, segments: engine.getSegments() })));
router.get('/cohorts', ah(async (req, res) => res.json({ ok: true, cohorts: engine.getCohortRetention() })));
router.get('/channels', ah(async (req, res) => res.json({ ok: true, channels: engine.getChannelLtv() })));
router.get('/products', ah(async (req, res) => res.json({ ok: true, products: engine.getProductLtv() })));
router.get('/warnings', ah(async (req, res) => res.json({ ok: true, warnings: engine.getEarlyWarnings() })));
router.get('/export/google-customer-match', ah(async (req, res) => res.json({ ok: true, ...engine.getValueBasedBiddingExport() })));
router.post('/predict', requireCreditsOnMutation('analytics-insight'), ah(async (req, res) => { const { customerId, rfmScore } = req.body; if (!customerId) return res.status(400).json({ ok: false, error: 'customerId required' }); res.json({ ok: true, ...engine.calcChurnProbability(customerId, rfmScore || 8) }); }));
router.post('/roi', requireCreditsOnMutation('analytics-insight'), ah(async (req, res) => { const { segment, campaignCost = 1000, revenuePerCustomer = 180 } = req.body; if (!segment) return res.status(400).json({ ok: false, error: 'segment required' }); res.json({ ok: true, ...engine.calcReactivationRoi(segment, campaignCost, revenuePerCustomer) }); }));
router.get('/churn-summary', ah(async (req, res) => res.json({ ok: true, ...engine.getChurnSummary() })));
router.post('/scenario', ah(async (req, res) => { const { repeatRateChange = 0.05 } = req.body; res.json({ ok: true, scenario: engine.ltvScenario(repeatRateChange) }); }));
router.use((err, req, res, next) => res.status(500).json({ ok: false, error: err.message }));
module.exports = router;
