'use strict';
const express = require('express');
const router = express.Router();
const verifyShopifySession = require('../../middleware/verifyShopifySession');
const { requireCreditsOnMutation } = require('../../core/creditMiddleware');
const engine = require('./engines/ltv-engine');
router.use(verifyShopifySession);
const ah = fn => (req, res, next) => Promise.resolve(fn(req, res, next)).catch(next);
router.get('/health', ah(async (req, res) => res.json({ ok: true, service: 'ltv-churn-predictor', v: '2.0.0' })));
router.get('/dashboard', ah(async (req, res) => res.json({ ok: true, ...(engine.getDashboardStats ? engine.getDashboardStats() : {}) })));
router.get('/predictions', ah(async (req, res) => res.json({ ok: true, ...(engine.getPredictions ? engine.getPredictions() : {}) })));
router.get('/segments', ah(async (req, res) => res.json({ ok: true, ...(engine.getSegments ? engine.getSegments() : {}) })));
router.post('/predict/:customerId', requireCreditsOnMutation('analytics-insight'), ah(async (req, res) => res.json({ ok: true, ...(engine.predictCustomer ? engine.predictCustomer(req.params.customerId) : { customerId: req.params.customerId, ltvPrediction: 280, churnRisk: 0.24 }) })));
router.use((err, req, res, next) => res.status(500).json({ ok: false, error: err.message }));
module.exports = router;
