'use strict';
const express = require('express');
const router = express.Router();
const verifyShopifySession = require('../../middleware/verifyShopifySession');
const { requireCreditsOnMutation } = require('../../core/creditMiddleware');
const ah = fn => (req, res, next) => Promise.resolve(fn(req, res, next)).catch(next);
router.use(verifyShopifySession);
const engine = require('./engines/forecasting-engine');
router.get('/health', ah(async (req, res) => res.json({ ok: true, service: 'inventory-forecasting', v: '2.0.0' })));
router.get('/seasonal-index', ah(async (req, res) => res.json({ ok: true, ...engine.getSeasonalIndex(req.query) })));
router.get('/stockout-risks', ah(async (req, res) => res.json({ ok: true, ...engine.getStockoutRisks(req.query) })));
router.get('/abc-xyz', ah(async (req, res) => res.json({ ok: true, ...engine.getAbcXyzMatrix(req.query) })));
router.get('/skus', ah(async (req, res) => res.json({ ok: true, ...engine.getSkus(req.query) })));
router.get('/skus/:id/forecast', ah(async (req, res) => res.json({ ok: true, ...engine.getForecast(req.params.id, req.query) })));
router.post('/safety-stock/calc', ah(async (req, res) => res.json({ ok: true, ...engine.calcSafetyStock(req.body) })));
router.post('/eoq/calc', ah(async (req, res) => res.json({ ok: true, ...engine.calcEoq(req.body) })));
router.post('/purchase-order/generate', requireCreditsOnMutation('blog-draft'), ah(async (req, res) => res.json({ ok: true, ...engine.generatePurchaseOrder(req.body) })));
router.post('/scenario/what-if', requireCreditsOnMutation('seo-scan'), ah(async (req, res) => res.json({ ok: true, ...engine.whatIfScenario(req.body) })));
router.use((err, req, res, next) => res.status(500).json({ ok: false, error: err.message }));
module.exports = router;

