'use strict';
const express = require('express');
const router = express.Router();
const verifyShopifySession = require('../../middleware/verifyShopifySession');
const engine = require('./engines/compliance-privacy-engine');
router.use(verifyShopifySession);
const ah = fn => (req, res, next) => Promise.resolve(fn(req, res, next)).catch(next);
router.get('/health', ah(async (req, res) => res.json({ ok: true, service: 'compliance-privacy-suite', v: '2.0.0' })));
router.get('/dashboard', ah(async (req, res) => res.json({ ok: true, ...engine.getDashboardStats() })));
router.get('/consents', ah(async (req, res) => res.json({ ok: true, consents: engine.getConsents(req.query) })));
router.get('/dsar', ah(async (req, res) => res.json({ ok: true, requests: engine.getDsarRequests(req.query) })));
router.get('/dsar/:id', ah(async (req, res) => { const d = engine.getDsarRequest(req.params.id); if (!d) return res.status(404).json({ ok: false, error: 'not found' }); res.json({ ok: true, request: d }); }));
router.post('/dsar', ah(async (req, res) => { const { type, customerEmail } = req.body; if (!type || !customerEmail) return res.status(400).json({ ok: false, error: 'type and customerEmail required' }); res.json({ ok: true, ...engine.createDsarRequest(type, customerEmail) }); }));
router.get('/compliance-checks', ah(async (req, res) => res.json({ ok: true, checks: engine.getComplianceChecks() })));
router.post('/customers/:id/delete', ah(async (req, res) => { if (!req.body.reason) return res.status(400).json({ ok: false, error: 'reason required' }); res.json({ ok: true, ...engine.deleteCustomerData(req.params.id, req.body.reason) }); }));
router.use((err, req, res, next) => res.status(500).json({ ok: false, error: err.message }));
module.exports = router;
