'use strict';
const express = require('express');
const router = express.Router();
const verifyShopifySession = require('../../middleware/verifyShopifySession');
const { requireCreditsOnMutation } = require('../../core/creditMiddleware');
const ah = fn => (req, res, next) => Promise.resolve(fn(req, res, next)).catch(next);
router.use(verifyShopifySession);
router.get('/health', ah(async (req, res) => res.json({ ok: true, service: 'data-warehouse-connector', v: '2.0.0' })));
const engine = require('./engines/data-warehouse-engine');
router.get('/dashboard', ah(async (req, res) => res.json({ ok: true, ...engine.getDashboardStats() })));
router.get('/connectors', ah(async (req, res) => res.json({ ok: true, connectors: engine.getConnectors(req.query) })));
router.get('/connectors/:id', ah(async (req, res) => { const c = engine.getConnector(req.params.id); if (!c) return res.status(404).json({ ok: false, error: 'not found' }); res.json({ ok: true, connector: c }); }));
router.get('/sync-jobs', ah(async (req, res) => res.json({ ok: true, jobs: engine.getSyncJobs(req.query) })));
router.get('/schema', ah(async (req, res) => res.json({ ok: true, tables: engine.getSchemaTables() })));
router.post('/sync', ah(async (req, res) => { const { connectorId, tables = [] } = req.body; if (!connectorId) return res.status(400).json({ ok: false, error: 'connectorId required' }); res.json({ ok: true, ...engine.triggerSync(connectorId, tables) }); }));
router.use((err, req, res, next) => res.status(500).json({ ok: false, error: err.message }));
module.exports = router;
