'use strict';
const express = require('express');
const router = express.Router();
const verifyShopifySession = require('../../middleware/verifyShopifySession');
const { requireCreditsOnMutation } = require('../../core/creditMiddleware');
const ah = fn => (req, res, next) => Promise.resolve(fn(req, res, next)).catch(next);
router.use(verifyShopifySession);
const engine = require('./engines/data-warehouse-engine');
router.get('/health', ah(async (req, res) => res.json({ ok: true, service: 'data-warehouse-connector', v: '2.0.0' })));
router.get('/dashboard', ah(async (req, res) => res.json({ ok: true, ...engine.getDashboardStats() })));
router.get('/sync-jobs', ah(async (req, res) => res.json({ ok: true, ...engine.getSyncJobs(req.query) })));
router.get('/connectors', ah(async (req, res) => res.json({ ok: true, ...engine.getConnectors(req.query) })));
router.get('/connectors/:id', ah(async (req, res) => { const item = engine.getConnector(req.params.id); if (!item) return res.status(404).json({ ok: false, error: 'not found' }); res.json({ ok: true, connector: item }); }));
router.get('/connectors/:id/schema', ah(async (req, res) => res.json({ ok: true, ...engine.getSchemaTables(req.params.id) })));
router.post('/connectors/test', ah(async (req, res) => res.json({ ok: true, ...engine.testConnection(req.body) })));
router.post('/sync-jobs/:id/trigger', ah(async (req, res) => res.json({ ok: true, ...engine.triggerSync(req.params.id) })));
router.post('/query/preview', requireCreditsOnMutation('seo-scan'), ah(async (req, res) => res.json({ ok: true, ...engine.previewQuery(req.body) })));
router.use((err, req, res, next) => res.status(500).json({ ok: false, error: err.message }));
module.exports = router;
