'use strict';
const express = require('express');
const router = express.Router();
const verifyShopifySession = require('../../middleware/verifyShopifySession');
const { requireCreditsOnMutation } = require('../../core/creditMiddleware');
const ah = fn => (req, res, next) => Promise.resolve(fn(req, res, next)).catch(next);
router.use(verifyShopifySession);
const engine = require('./engines/email-deliverability-engine');
router.get('/health', ah(async (req, res) => res.json({ ok: true, service: 'email-deliverability', v: '2.0.0' })));
router.get('/dashboard', ah(async (req, res) => res.json({ ok: true, ...engine.getDashboardStats() })));
router.get('/recommendations', ah(async (req, res) => res.json({ ok: true, ...engine.getRecommendations() })));
router.get('/isp-metrics', ah(async (req, res) => res.json({ ok: true, ...engine.getIspMetrics(req.query) })));
router.get('/blacklists', ah(async (req, res) => res.json({ ok: true, ...engine.getBlacklists(req.query) })));
router.get('/domains', ah(async (req, res) => res.json({ ok: true, ...engine.getDomains(req.query) })));
router.post('/domains/check', ah(async (req, res) => res.json({ ok: true, ...engine.checkDomain(req.body) })));
router.use((err, req, res, next) => res.status(500).json({ ok: false, error: err.message }));
module.exports = router;
