'use strict';
const express = require('express');
const router = express.Router();
const verifyShopifySession = require('../../middleware/verifyShopifySession');
const { requireCreditsOnMutation } = require('../../core/creditMiddleware');
const ah = fn => (req, res, next) => Promise.resolve(fn(req, res, next)).catch(next);
router.use(verifyShopifySession);
router.get('/health', ah(async (req, res) => res.json({ ok: true, service: 'email-deliverability', v: '2.0.0' })));
const engine = require('./engines/email-deliverability-engine');
router.get('/dashboard', ah(async (req, res) => res.json({ ok: true, ...engine.getDashboardStats() })));
router.get('/domains', ah(async (req, res) => res.json({ ok: true, domains: engine.getDomains() })));
router.get('/blacklists', ah(async (req, res) => res.json({ ok: true, blacklists: engine.getBlacklists() })));
router.get('/isp-metrics', ah(async (req, res) => res.json({ ok: true, ispMetrics: engine.getIspMetrics() })));
router.get('/recommendations', ah(async (req, res) => res.json({ ok: true, recommendations: engine.getRecommendations() })));
router.post('/check-domain', ah(async (req, res) => { const { domain } = req.body; if (!domain) return res.status(400).json({ ok: false, error: 'domain required' }); res.json({ ok: true, ...engine.checkDomain(domain) }); }));
router.use((err, req, res, next) => res.status(500).json({ ok: false, error: err.message }));
module.exports = router;
