'use strict';
const express = require('express');
const router = express.Router();
const verifyShopifySession = require('../../middleware/verifyShopifySession');
const { requireCreditsOnMutation } = require('../../core/creditMiddleware');
const ah = fn => (req, res, next) => Promise.resolve(fn(req, res, next)).catch(next);
router.use(verifyShopifySession);
router.get('/health', ah(async (req, res) => res.json({ ok: true, service: 'finance-autopilot', v: '2.0.0' })));
const engine = require('./engines/finance-autopilot-engine');
router.get('/dashboard', ah(async (req, res) => res.json({ ok: true, ...engine.getDashboardStats() })));
router.get('/invoices', ah(async (req, res) => res.json({ ok: true, invoices: engine.getInvoices(req.query) })));
router.get('/reconciliation', ah(async (req, res) => res.json({ ok: true, reconciliation: engine.getBankReconciliation() })));
router.get('/ap-dashboard', ah(async (req, res) => res.json({ ok: true, ...engine.getApDashboard() })));
router.use((err, req, res, next) => res.status(500).json({ ok: false, error: err.message }));
module.exports = router;
