'use strict';
const express = require('express');
const router = express.Router();
const verifyShopifySession = require('../../middleware/verifyShopifySession');
const { requireCreditsOnMutation } = require('../../core/creditMiddleware');
const engine = require('./engines/finance-autopilot-engine');
router.use(verifyShopifySession);
const ah = fn => (req, res, next) => Promise.resolve(fn(req, res, next)).catch(next);
router.get('/health', ah(async (req, res) => res.json({ ok: true, service: 'finance-autopilot', v: '2.0.0' })));
router.get('/dashboard', ah(async (req, res) => res.json({ ok: true, ...(engine.getDashboardStats ? engine.getDashboardStats() : {}) })));
router.get('/cashflow', ah(async (req, res) => res.json({ ok: true, ...(engine.getCashflow ? engine.getCashflow() : {}) })));
router.get('/ap', ah(async (req, res) => res.json({ ok: true, ...(engine.getAccountsPayable ? engine.getAccountsPayable() : {}) })));
router.get('/ar', ah(async (req, res) => res.json({ ok: true, ...(engine.getAccountsReceivable ? engine.getAccountsReceivable() : {}) })));
router.post('/forecast', requireCreditsOnMutation('analytics-insight'), ah(async (req, res) => res.json({ ok: true, ...(engine.forecast ? engine.forecast(req.body) : { forecastId: 'fc_' + Date.now() }) })));
router.use((err, req, res, next) => res.status(500).json({ ok: false, error: err.message }));
module.exports = router;
