'use strict';
const express = require('express');
const router = express.Router();
const verifyShopifySession = require('../../middleware/verifyShopifySession');
const { requireCreditsOnMutation } = require('../../core/creditMiddleware');
const ah = fn => (req, res, next) => Promise.resolve(fn(req, res, next)).catch(next);
router.use(verifyShopifySession);
const engine = require('./engines/finance-autopilot-engine');
router.get('/health', ah(async (req, res) => res.json({ ok: true, service: 'finance-autopilot', v: '2.0.0' })));
router.get('/ap-dashboard', ah(async (req, res) => res.json({ ok: true, ...engine.getApDashboard() })));
router.get('/bank-reconciliation', ah(async (req, res) => res.json({ ok: true, ...engine.getBankReconciliation(req.query) })));
router.get('/invoices', ah(async (req, res) => res.json({ ok: true, ...engine.getInvoices(req.query) })));
router.post('/gl-account/map', ah(async (req, res) => res.json({ ok: true, ...engine.mapGlAccount(req.body) })));
router.post('/duplicates/detect', ah(async (req, res) => res.json({ ok: true, ...engine.detectDuplicates(req.body) })));
router.post('/shopify-payout/reconcile', ah(async (req, res) => res.json({ ok: true, ...engine.reconcileShopifyPayout(req.body) })));
router.use((err, req, res, next) => res.status(500).json({ ok: false, error: err.message }));
module.exports = router;
