'use strict';
const express = require('express');
const router = express.Router();
const verifyShopifySession = require('../../middleware/verifyShopifySession');
const { requireCreditsOnMutation } = require('../../core/creditMiddleware');
const ah = fn => (req, res, next) => Promise.resolve(fn(req, res, next)).catch(next);
router.use(verifyShopifySession);
const engine = require('./engines/automation-templates-engine');
router.get('/health', ah(async (req, res) => res.json({ ok: true, service: 'automation-templates', v: '2.0.0' })));
router.get('/stats', ah(async (req, res) => res.json({ ok: true, ...engine.getStats() })));
router.get('/categories', ah(async (req, res) => res.json({ ok: true, categories: engine.getCategories() })));
router.get('/templates', ah(async (req, res) => res.json({ ok: true, ...engine.getTemplates(req.query) })));
router.get('/templates/:id', ah(async (req, res) => { const item = engine.getTemplate(req.params.id); if (!item) return res.status(404).json({ ok: false, error: 'not found' }); res.json({ ok: true, template: item }); }));
router.post('/templates/:id/install', ah(async (req, res) => res.json({ ok: true, ...engine.installTemplate(req.params.id, req.body) })));
router.post('/templates/:id/preview', ah(async (req, res) => res.json({ ok: true, ...engine.previewTemplate(req.params.id) })));
router.use((err, req, res, next) => res.status(500).json({ ok: false, error: err.message }));
module.exports = router;
