'use strict';
const express = require('express');
const router = express.Router();
const verifyShopifySession = require('../../middleware/verifyShopifySession');
const { requireCreditsOnMutation } = require('../../core/creditMiddleware');
const ah = fn => (req, res, next) => Promise.resolve(fn(req, res, next)).catch(next);
router.use(verifyShopifySession);
const engine = require('./engines/affiliate-engine');
router.get('/health', ah(async (req, res) => res.json({ ok: true, service: 'affiliate-partner-management', v: '2.0.0' })));
router.get('/dashboard', ah(async (req, res) => res.json({ ok: true, ...engine.getDashboardStats() })));
router.get('/payouts', ah(async (req, res) => res.json({ ok: true, ...engine.getPayouts(req.query) })));
router.get('/tiers', ah(async (req, res) => res.json({ ok: true, ...engine.getTiers() })));
router.get('/affiliates', ah(async (req, res) => res.json({ ok: true, ...engine.getAffiliates(req.query) })));
router.get('/affiliates/:id', ah(async (req, res) => { const item = engine.getAffiliate(req.params.id); if (!item) return res.status(404).json({ ok: false, error: 'not found' }); res.json({ ok: true, affiliate: item }); }));
router.post('/affiliates/:id/link', ah(async (req, res) => res.json({ ok: true, ...engine.generateAffiliateLink(req.params.id, req.body) })));
router.use((err, req, res, next) => res.status(500).json({ ok: false, error: err.message }));
module.exports = router;
