'use strict';
const express = require('express');
const router = express.Router();
const verifyShopifySession = require('../../middleware/verifyShopifySession');
const { requireCreditsOnMutation } = require('../../core/creditMiddleware');
const ah = fn => (req, res, next) => Promise.resolve(fn(req, res, next)).catch(next);
router.use(verifyShopifySession);
const engine = require('./engines/self-service-analytics-engine');
router.get('/health', ah(async (req, res) => res.json({ ok: true, service: 'self-service-analytics', v: '2.0.0' })));
router.get('/dashboard', ah(async (req, res) => res.json({ ok: true, ...engine.getDashboardStats() })));
router.get('/metrics-catalog', ah(async (req, res) => res.json({ ok: true, ...engine.getMetricsCatalog() })));
router.get('/queries', ah(async (req, res) => res.json({ ok: true, queries: engine.getQueries() })));
router.get('/reports', ah(async (req, res) => res.json({ ok: true, ...engine.getReports(req.query) })));
router.get('/reports/:id', ah(async (req, res) => { const item = engine.getReport(req.params.id); if (!item) return res.status(404).json({ ok: false, error: 'not found' }); res.json({ ok: true, report: item }); }));
router.post('/query/run', requireCreditsOnMutation('seo-scan'), ah(async (req, res) => res.json({ ok: true, ...engine.runQuery(req.body) })));
router.post('/reports/:id/export', ah(async (req, res) => res.json({ ok: true, ...engine.exportReport(req.params.id, req.body) })));
router.use((err, req, res, next) => res.status(500).json({ ok: false, error: err.message }));
module.exports = router;
