'use strict';
const express = require('express');
const router = express.Router();
const verifyShopifySession = require('../../middleware/verifyShopifySession');
const { requireCreditsOnMutation } = require('../../core/creditMiddleware');
const engine = require('./engines/advanced-finance-engine');
router.use(verifyShopifySession);
const ah = fn => (req, res, next) => Promise.resolve(fn(req, res, next)).catch(next);
router.get('/health', ah(async (req, res) => res.json({ ok: true, service: 'advanced-finance-inventory-planning', v: '2.0.0' })));
router.get('/dashboard', ah(async (req, res) => res.json({ ok: true, ...(engine.getDashboardStats ? engine.getDashboardStats() : {}) })));
router.get('/forecast', ah(async (req, res) => res.json({ ok: true, ...(engine.getForecast ? engine.getForecast() : engine.getInventoryForecast ? engine.getInventoryForecast() : {}) })));
router.get('/scenarios', ah(async (req, res) => res.json({ ok: true, ...(engine.getScenarios ? engine.getScenarios() : {}) })));
router.post('/plan', requireCreditsOnMutation('analytics-insight'), ah(async (req, res) => res.json({ ok: true, ...(engine.generatePlan ? engine.generatePlan(req.body) : { status: 'generated', planId: 'plan_' + Date.now() }) })));
router.use((err, req, res, next) => res.status(500).json({ ok: false, error: err.message }));
module.exports = router;
