'use strict';
const express = require('express');
const router = express.Router();
const verifyShopifySession = require('../../middleware/verifyShopifySession');
const { requireCreditsOnMutation } = require('../../core/creditMiddleware');
const engine = require('./engines/advanced-finance-engine');
const ah = fn => (req, res, next) => Promise.resolve(fn(req, res, next)).catch(next);
router.use(verifyShopifySession);
router.get('/health', ah(async (req, res) => res.json({ ok: true, service: 'advanced-finance-inventory-planning', v: '2.0.0' })));
router.get('/dashboard', ah(async (req, res) => res.json({ ok: true, ...engine.getDashboardStats() })));
router.get('/pnl', ah(async (req, res) => res.json({ ok: true, pnl: engine.getPnl() })));
router.get('/inventory', ah(async (req, res) => res.json({ ok: true, inventory: engine.getInventory() })));
router.get('/otb', ah(async (req, res) => res.json({ ok: true, otb: engine.getOtb() })));
router.get('/ccc', ah(async (req, res) => res.json({ ok: true, ccc: engine.getCccAnalysis() })));
router.get('/budget-vs-actuals', ah(async (req, res) => res.json({ ok: true, budgetVsActuals: engine.getBudgetVsActuals() })));
router.post('/montecarlo', requireCreditsOnMutation('analytics-insight'), ah(async (req, res) => { const { simulations = 1000 } = req.body; res.json({ ok: true, monteCarlo: engine.runMonteCarlo(simulations) }); }));
router.use((err, req, res, next) => res.status(500).json({ ok: false, error: err.message }));
module.exports = router;
