// This file has been removed to avoid confusion and ensure a single source of truth.
// Auto-generated tool meta registry for Aura Core
// Each object: { id, name, description, category }

const toolsMeta = [
  // ...existing tool meta entries...
  // The following are auto-added for missing tools. Please update descriptions and categories as needed.
  { id: "abtestingsuite", name: "A/B Testing Suite", description: "A/B test creation, management, and analytics.", category: "Analytics" },
  { id: "advanced-analytics-attribution", name: "Advanced Analytics Attribution", description: "Advanced attribution analytics.", category: "Analytics" },
  { id: "advanced-finance-inventory-planning", name: "Advanced Finance Inventory Planning", description: "Finance and inventory planning.", category: "Finance" },
  { id: "advanced-personalization-engine", name: "Advanced Personalization Engine", description: "Personalization engine for marketing.", category: "Marketing" },
  { id: "ai-content-brief-generator", name: "AI Content Brief Generator", description: "AI-powered content brief generation.", category: "Content / AI" },
  { id: "aura-api-sdk", name: "Aura API SDK", description: "Generates API SDK configuration snippets.", category: "Development" },
  { id: "aura-operations-ai", name: "Aura Operations AI", description: "Generates operations insights and checklists.", category: "Operations / AI" },
  { id: "automation-templates", name: "Automation Templates", description: "Templates for automation workflows.", category: "Automation" },
  { id: "backlink-explorer", name: "Backlink Explorer", description: "Explore and analyze backlinks.", category: "SEO" },
  { id: "blog-draft-engine", name: "Blog Draft Engine", description: "Generate a full SEO-focused blog article draft from a single blog idea.", category: "Content · Drafts" },
  { id: "brand-mention-tracker", name: "Brand Mention Tracker", description: "Track brand mentions across the web.", category: "Brand" },
  { id: "churn-prediction-playbooks", name: "Churn Prediction Playbooks", description: "Churn prediction and retention playbooks.", category: "Analytics" },
  { id: "collaboration-approval-workflows", name: "Collaboration Approval Workflows", description: "Collaboration and approval workflows.", category: "Collaboration" },
  { id: "competitive-analysis", name: "Competitive Analysis", description: "Competitive analysis and benchmarking.", category: "Analytics" },
  { id: "conditional-logic-automation", name: "Conditional Logic Automation", description: "Conditional logic for automations.", category: "Automation" },
  { id: "consent-privacy-management", name: "Consent & Privacy Management", description: "Consent and privacy management tools.", category: "Compliance" },
  { id: "content-health-auditor", name: "Content Health Auditor", description: "Content health and quality auditing.", category: "Content" },
  { id: "content-scoring-optimization", name: "Content Scoring Optimization", description: "Optimize content scoring.", category: "Content" },
  { id: "creative-automation-engine", name: "Creative Automation Engine", description: "Generates creative hooks and angles.", category: "Marketing / Creative" },
  { id: "custom-dashboard-builder", name: "Custom Dashboard Builder", description: "Build custom dashboards.", category: "Analytics" },
  { id: "customer-data-platform", name: "Customer Data Platform", description: "Customer data management platform.", category: "Analytics" },
  { id: "customer-journey-mapping", name: "Customer Journey Mapping", description: "Map customer journeys.", category: "Analytics" },
  { id: "customer-segmentation-engine", name: "Customer Segmentation Engine", description: "Segment customers for analytics.", category: "Analytics" },
  { id: "customer-support-ai", name: "Customer Support AI", description: "Assists with customer support tasks using AI.", category: "Support / AI" },
  { id: "daily-cfo-pack", name: "Daily CFO Pack", description: "Daily CFO analytics pack.", category: "Finance" },
  { id: "data-enrichment-suite", name: "Data Enrichment Suite", description: "Data enrichment tools.", category: "Data" },
  { id: "data-warehouse-connector", name: "Data Warehouse Connector", description: "Connect to data warehouses.", category: "Data" },
  { id: "dynamic-pricing-engine", name: "Dynamic Pricing Engine", description: "Dynamic pricing optimization.", category: "Pricing" },
  { id: "email-automation-builder", name: "Email Automation Builder", description: "Builds email automation flows and blueprints.", category: "Email / Automation" },
  { id: "entity-topic-explorer", name: "Entity Topic Explorer", description: "Explore entity topics.", category: "SEO" },
  { id: "finance-autopilot", name: "Finance Autopilot", description: "Automated finance snapshot and margin analysis.", category: "Finance" },
  { id: "image-alt-media-seo", name: "Image Alt / Media SEO", description: "Generates image alt text and media SEO recommendations.", category: "SEO" },
  { id: "inbox-assistant", name: "Inbox Assistant", description: "Assists with inbox management and replies.", category: "Support" },
  { id: "inbox-reply-assistant", name: "Inbox Reply Assistant", description: "Generates reply templates for customer support inbox.", category: "Support" },
  { id: "internal-linking-suggestions", name: "Internal Linking Suggestions", description: "Suggest internal links.", category: "SEO" },
  { id: "internal-link-optimizer", name: "Internal Link Optimizer", description: "Suggests internal links for SEO and navigation.", category: "SEO" },
  { id: "inventory-forecasting", name: "Inventory Forecasting", description: "Forecast inventory needs.", category: "Operations" },
  { id: "inventory-supplier-sync", name: "Inventory Supplier Sync", description: "Syncs inventory data with suppliers.", category: "Operations" },
  { id: "keyword-research-suite", name: "Keyword Research Suite", description: "Keyword research tools.", category: "SEO" },
  { id: "klaviyo-flow-automation", name: "Klaviyo Flow Automation", description: "Blueprints for Klaviyo automation flows.", category: "Email / Automation" },
  { id: "link-intersect-outreach", name: "Link Intersect Outreach", description: "Link intersect and outreach tools.", category: "SEO" },
  { id: "local-seo-toolkit", name: "Local SEO Toolkit", description: "Local SEO optimization tools.", category: "SEO" },
  { id: "ltv-churn-predictor", name: "LTV / Churn Predictor", description: "Predicts lifetime value and churn risk.", category: "Analytics" },
  { id: "multi-channel-optimizer", name: "Multi-Channel Optimizer", description: "Splits marketing budget across multiple channels.", category: "Marketing" },
  { id: "on-page-seo-engine", name: "On-Page SEO Engine", description: "Optimizes on-page SEO elements.", category: "SEO" },
  { id: "personalization-recommendation-engine", name: "Personalization Recommendation Engine", description: "Personalized recommendations engine.", category: "Marketing" },
  { id: "product-seo-engine", name: "Product SEO Engine", description: "Generate SEO titles, meta descriptions, slugs and keyword sets for products.", category: "SEO" },
  { id: "rank-visibility-tracker", name: "Rank & Visibility Tracker", description: "Tracks search rank and visibility.", category: "SEO" },
  { id: "reporting-alerts", name: "Reporting Alerts", description: "Reporting and alerting tools.", category: "Analytics" },
  { id: "reporting-integrations", name: "Reporting Integrations", description: "Integrate reporting tools.", category: "Analytics" },
  { id: "returns-rma-automation", name: "Returns/RMA Automation", description: "Automates returns and RMA processes.", category: "Operations" },
  { id: "review-ugc-engine", name: "Review UGC Engine", description: "Generates review prompts and UGC questions.", category: "Reviews / UGC" },
  { id: "scheduled-export", name: "Scheduled Export", description: "Schedule data exports.", category: "Data" },
  { id: "schema-rich-results-engine", name: "Schema Rich Results Engine", description: "Generates schema.org rich results snippets.", category: "SEO" },
  { id: "self-service-portal", name: "Self Service Portal", description: "Customer self-service portal.", category: "Support" },
  { id: "self-service-support-portal", name: "Self Service Support Portal", description: "Support self-service portal.", category: "Support" },
  { id: "seo-site-crawler", name: "SEO Site Crawler", description: "Crawl and audit SEO for sites.", category: "SEO" },
  { id: "serp-tracker", name: "SERP Tracker", description: "Track SERP rankings.", category: "SEO" },
  { id: "site-audit-health", name: "Site Audit Health", description: "Site health auditing tools.", category: "SEO" },
  { id: "social-media-analytics-listening", name: "Social Media Analytics & Listening", description: "Social media analytics and listening.", category: "Social" },
  { id: "social-scheduler-content-engine", name: "Social Scheduler Content Engine", description: "Automates social content scheduling.", category: "Social / Content" },
  { id: "technical-seo-auditor", name: "Technical SEO Auditor", description: "Performs technical SEO health checks.", category: "SEO" },
  { id: "tool-scaffold", name: "Tool Scaffold", description: "Scaffold for new tools.", category: "Development" },
  { id: "upsell-cross-sell-engine", name: "Upsell/Cross-Sell Engine", description: "Upsell and cross-sell recommendations.", category: "Sales" },
  { id: "visual-workflow-builder", name: "Visual Workflow Builder", description: "Visual builder for workflows.", category: "Automation" },
  { id: "webhook-api-triggers", name: "Webhook & API Triggers", description: "Webhook and API trigger management.", category: "Integration" },
  { id: "weekly-blog-content-engine", name: "Weekly Blog Content Engine", description: "Generate a simple weekly content plan with SEO-ready blog titles, meta descriptions, slugs and primary keywords.", category: "SEO / Content" },
  { id: "winback-empty-state", name: "Winback Empty State", description: "Winback empty state UI.", category: "Email / Automation" },
  { id: "winback-feature-card", name: "Winback Feature Card", description: "Winback feature card UI.", category: "Email / Automation" },
  { id: "winback-help-docs", name: "Winback Help Docs", description: "Winback help documentation.", category: "Email / Automation" },
  { id: "workflow-automation-builder", name: "Workflow Automation Builder", description: "Build and automate workflows.", category: "Automation" },
  { id: "workflow-orchestrator", name: "Workflow Orchestrator", description: "Orchestrates multi-step automation workflows.", category: "Automation" }
];

module.exports = toolsMeta;
