'use strict';
const express = require('express');
const router = express.Router();
const verifyShopifySession = require('../../middleware/verifyShopifySession');
const engine = require('./engines/daily-cfo-engine');
router.use(verifyShopifySession);
const ah = fn => (req, res, next) => Promise.resolve(fn(req, res, next)).catch(next);
router.get('/health', ah(async (req, res) => res.json({ ok: true, service: 'daily-cfo-pack', v: '2.0.0' })));
router.get('/dashboard', ah(async (req, res) => res.json({ ok: true, ...(engine.getDashboardStats ? engine.getDashboardStats() : {}) })));
router.get('/pack', ah(async (req, res) => res.json({ ok: true, ...(engine.getDailyPack ? engine.getDailyPack() : engine.getPack ? engine.getPack() : {}) })));
router.get('/metrics', ah(async (req, res) => res.json({ ok: true, ...(engine.getMetrics ? engine.getMetrics() : {}) })));
router.get('/alerts', ah(async (req, res) => res.json({ ok: true, ...(engine.getAlerts ? engine.getAlerts() : {}) })));
router.use((err, req, res, next) => res.status(500).json({ ok: false, error: err.message }));
module.exports = router;
