'use strict';
const express = require('express');
const router = express.Router();
const verifyShopifySession = require('../../middleware/verifyShopifySession');
const { requireCreditsOnMutation } = require('../../core/creditMiddleware');
const ah = fn => (req, res, next) => Promise.resolve(fn(req, res, next)).catch(next);
router.use(verifyShopifySession);
const engine = require('./engines/daily-cfo-engine');
router.get('/health', ah(async (req, res) => res.json({ ok: true, service: 'daily-cfo-pack', v: '2.0.0' })));
router.get('/thresholds', ah(async (req, res) => res.json({ ok: true, ...engine.getAdaptiveThresholds() })));
router.get('/benchmarks', ah(async (req, res) => res.json({ ok: true, ...engine.getCompetitiveBenchmarks() })));
router.get('/revenue-ticker', ah(async (req, res) => res.json({ ok: true, ...engine.getRevenueTicker() })));
router.get('/briefing', ah(async (req, res) => res.json({ ok: true, ...engine.getBriefing(req.query) })));
router.get('/kpis', ah(async (req, res) => res.json({ ok: true, ...engine.getKpis(req.query) })));
router.post('/query', requireCreditsOnMutation('seo-scan'), ah(async (req, res) => res.json({ ok: true, ...engine.answerNlpQuery(req.body) })));
router.post('/board-pack', requireCreditsOnMutation('blog-draft'), ah(async (req, res) => res.json({ ok: true, ...engine.generateBoardPack(req.body) })));
router.use((err, req, res, next) => res.status(500).json({ ok: false, error: err.message }));
module.exports = router;
