'use strict';
const express = require('express');
const router = express.Router();
const verifyShopifySession = require('../../middleware/verifyShopifySession');
const { requireCreditsOnMutation } = require('../../core/creditMiddleware');
const engine = require('./engines/daily-cfo-engine');
const ah = fn => (req, res, next) => Promise.resolve(fn(req, res, next)).catch(next);
router.use(verifyShopifySession);
router.get('/health', ah(async (req, res) => res.json({ ok: true, service: 'daily-cfo-pack', v: '2.0.0' })));
router.get('/dashboard', ah(async (req, res) => res.json({ ok: true, ...engine.getDashboardStats() })));
router.get('/kpis', ah(async (req, res) => res.json({ ok: true, kpis: engine.getTodayKpis() })));
router.get('/pnl', ah(async (req, res) => res.json({ ok: true, pnl: engine.getPnl() })));
router.get('/cashflow', ah(async (req, res) => res.json({ ok: true, cashflow: engine.getCashflow() })));
router.get('/briefing', ah(async (req, res) => res.json({ ok: true, briefing: engine.getDailyBriefing() })));
router.get('/thresholds', ah(async (req, res) => res.json({ ok: true, thresholds: engine.getAdaptiveThresholds() })));
router.get('/benchmarks', ah(async (req, res) => res.json({ ok: true, benchmarks: engine.getCompetitiveBenchmarks() })));
router.use((err, req, res, next) => res.status(500).json({ ok: false, error: err.message }));
module.exports = router;
