// Auto-generated tool meta registry for Aura Core
// Each object: { id, name, description, category }


const toolsMeta = [
  // --- Deduplicated flagship/advanced tool UIs ---
  { id: "advanced-personalization-engine", name: "Advanced Personalization Engine", description: "AI-powered real-time content/product personalization.", category: "Personalization / AI" },
  { id: "advanced-finance-inventory-planning", name: "Advanced Finance & Inventory Planning", description: "Advanced financial and inventory planning analytics.", category: "Finance / Analytics" },
  { id: "advanced-analytics-attribution", name: "Advanced Analytics Attribution", description: "Multi-touch attribution and advanced analytics.", category: "Analytics" },
  { id: "ai-content-brief-generator", name: "AI Content Brief Generator", description: "Instantly generate detailed content briefs with AI.", category: "Content / AI" },
  { id: "ab-testing-suite", name: "AI-Powered A/B Testing Suite", description: "Automated test setup, analysis, and optimization.", category: "Testing / AI" },
  { id: "schema-rich-results-engine", name: "Schema Rich Results Engine", description: "Generates schema.org rich results snippets.", category: "SEO" },
  { id: "self-service-portal", name: "Self-Service Portal", description: "Branded portal for merchants to manage integrations, billing, and support.", category: "Portal" },
  { id: "scheduled-export", name: "Scheduled PDF/CSV Exports", description: "Schedule PDF/CSV exports of your reports and dashboards.", category: "Reporting / Export" },
  { id: "review-ugc-engine", name: "Review UGC Engine", description: "Generates review prompts and UGC questions.", category: "Reviews / UGC" },
  { id: "returns-rma-automation", name: "Returns/RMA Automation", description: "Automates returns and RMA processes.", category: "Operations" },
  { id: "reporting-integrations", name: "Reporting Integrations", description: "Integrate reporting with Slack, Teams, Email, and Push notifications.", category: "Reporting / Integration" },
  { id: "reporting-alerts", name: "Reporting Alerts", description: "Set up and manage reporting alerts and notifications.", category: "Reporting / Alerts" },
  { id: "rank-visibility-tracker", name: "Rank & Visibility Tracker", description: "Tracks search rank and visibility.", category: "SEO" },
  { id: "product-seo-engine", name: "Product SEO Engine", description: "Generate SEO titles, meta descriptions, slugs and keyword sets for products.", category: "SEO" },
  { id: "personalization-recommendation-engine", name: "Personalization Recommendation Engine", description: "AI-driven product/content recommendations.", category: "Personalization / AI" },
  { id: "on-page-seo-engine", name: "On-Page SEO Engine", description: "Optimizes on-page SEO elements.", category: "SEO" },
  { id: "multi-channel-optimizer", name: "Multi-Channel Optimizer", description: "Splits marketing budget across multiple channels.", category: "Marketing" },
  { id: "ltv-churn-predictor", name: "LTV / Churn Predictor", description: "Predicts lifetime value and churn risk.", category: "Analytics" },
  { id: "self-service-support-portal", name: "Self-Service Support Portal", description: "Support portal for merchants and customers.", category: "Support / Portal" },
  { id: "weekly-blog-content-engine", name: "Weekly Blog Content Engine", description: "Generate a simple weekly content plan with SEO-ready blog titles, meta descriptions, slugs and primary keywords.", category: "SEO / Content" },
  { id: "webhook-api-triggers", name: "Webhook & External API Triggers", description: "Trigger automations from webhooks and external APIs.", category: "Automation / Integration" },
  { id: "visual-workflow-builder", name: "Visual Workflow Automation Builder", description: "Drag-and-drop workflow builder for cross-tool automations.", category: "Automation" },
  { id: "upsell-cross-sell-engine", name: "AI-Powered Upsell/Cross-sell Engine", description: "Boost revenue with AI-driven upsell and cross-sell recommendations.", category: "E-commerce / AI" },
  { id: "inventory-forecasting", name: "Inventory Forecasting", description: "Predict inventory needs and optimize stock levels.", category: "E-commerce / Analytics" },
  { id: "custom-dashboard-builder", name: "Custom Dashboard Builder", description: "Build custom dashboards for your reporting needs.", category: "Reporting / Visualization" },
  { id: "automation-templates", name: "Prebuilt Automation Templates", description: "Ready-to-use workflow and automation templates.", category: "Automation" },
  { id: "conditional-logic-automation", name: "Conditional Logic & Branching", description: "Add conditional logic and branching to your automations.", category: "Automation" },
  { id: "data-warehouse-connector", name: "Data Warehouse/BI Connector", description: "Integrate with BigQuery, Snowflake, Looker, etc., for advanced analytics.", category: "Analytics / Integration" },
  { id: "consent-privacy-management", name: "Consent & Privacy Management", description: "Automated GDPR/CCPA compliance, consent tracking, and audit logs.", category: "Compliance" },
  { id: "entity-topic-explorer", name: "Entity/Topic Explorer", description: "Semantic SEO: discover entities and topics for your content.", category: "SEO / AI" },
  { id: "internal-linking-suggestions", name: "Automated Internal Linking Suggestions", description: "AI-powered suggestions for internal links to boost SEO.", category: "SEO / AI" },
  { id: "brand-mention-tracker", name: "Brand Mention Tracker", description: "Track brand mentions across the web and social media.", category: "Analytics / Brand" },
  { id: "local-seo-toolkit", name: "Local SEO Toolkit", description: "Tools for GMB, citations, reviews, and local rankings.", category: "SEO / Local" },
  { id: "abandoned-checkout-winback", name: "Abandoned Checkout Winback", description: "Recover abandoned carts with automated winback campaigns.", category: "E-commerce / Automation" },
  { id: "ai-launch-planner", name: "AI Launch Planner", description: "Plan and optimize product launches using AI insights.", category: "Product / AI" },
  { id: "ai-support-assistant", name: "AI Support Assistant", description: "Automate and enhance customer support with AI.", category: "Support / AI" },
  { id: "backlink-explorer", name: "Backlink Explorer", description: "Analyze and discover backlink opportunities for SEO.", category: "SEO / Analytics" },
  { id: "blog-draft-engine", name: "Blog Draft Engine", description: "Generate and manage blog drafts with AI assistance.", category: "Content / AI" },
  { id: "brand-intelligence-layer", name: "Brand Intelligence Layer", description: "Gain insights into brand performance and reputation.", category: "Analytics / Brand" },
  { id: "churn-prediction-playbooks", name: "Churn Prediction Playbooks", description: "Predict and reduce customer churn with actionable playbooks.", category: "Analytics / Retention" },
  { id: "collaboration-approval-workflows", name: "Collaboration & Approval Workflows", description: "Streamline collaboration and approval processes across teams.", category: "Workflow / Collaboration" },
  { id: "competitive-analysis", name: "Competitive Analysis", description: "Analyze competitors and market trends for strategic advantage.", category: "Analytics / Strategy" },
  { id: "content-health-auditor", name: "Content Health Auditor", description: "Audit and optimize content health for better performance.", category: "Content / Analytics" },
  { id: "content-scoring-optimization", name: "Content Scoring & Optimization", description: "Score and optimize content for SEO and engagement.", category: "Content / SEO" },
  { id: "creative-automation-engine", name: "Creative Automation Engine", description: "Automate creative asset generation and management.", category: "Content / Automation" },
  { id: "customer-data-platform", name: "Customer Data Platform", description: "Centralize and analyze customer data for insights.", category: "Analytics / Customer" },
  { id: "customer-journey-mapping", name: "Customer Journey Mapping", description: "Visualize and optimize customer journeys.", category: "Analytics / Customer" },
  { id: "customer-segmentation-engine", name: "Customer Segmentation Engine", description: "Segment customers for targeted marketing and analysis.", category: "Analytics / Customer" },
  { id: "customer-support-ai", name: "Customer Support AI", description: "AI-powered customer support automation and analytics.", category: "Support / AI" },
  { id: "daily-cfo-pack", name: "Daily CFO Pack", description: "Automate daily financial reporting and insights.", category: "Finance / Automation" },
  { id: "data-enrichment-suite", name: "Data Enrichment Suite", description: "Enrich and validate data for better accuracy.", category: "Analytics / Data" },
  { id: "data-warehouse-connector", name: "Data Warehouse Connector", description: "Connect and sync with data warehouses and BI tools.", category: "Analytics / Integration" },
  { id: "dynamic-pricing-engine", name: "Dynamic Pricing Engine", description: "Automate and optimize pricing strategies with AI.", category: "E-commerce / AI" },
  { id: "email-automation-builder", name: "Email Automation Builder", description: "Build and automate email campaigns and flows.", category: "Marketing / Automation" },
  { id: "entity-topic-explorer", name: "Entity Topic Explorer", description: "Explore and analyze entities/topics for SEO.", category: "SEO / AI" },
  { id: "finance-autopilot", name: "Finance Autopilot", description: "Automate financial operations and reporting.", category: "Finance / Automation" },
  { id: "image-alt-media-seo", name: "Image Alt Media SEO", description: "Optimize image alt text and media for SEO.", category: "SEO / Media" },
  { id: "inbox-assistant", name: "Inbox Assistant", description: "Automate inbox management and smart replies.", category: "Productivity / AI" },
  { id: "inbox-reply-assistant", name: "Inbox Reply Assistant", description: "AI-powered reply suggestions for inboxes.", category: "Productivity / AI" },
  { id: "internal-link-optimizer", name: "Internal Link Optimizer", description: "Optimize internal linking for SEO and navigation.", category: "SEO / Automation" },
  { id: "inventory-supplier-sync", name: "Inventory Supplier Sync", description: "Sync inventory data with suppliers and vendors.", category: "E-commerce / Integration" },
  { id: "keyword-research-suite", name: "Keyword Research Suite", description: "Comprehensive keyword research and analysis tools.", category: "SEO / Research" },
  { id: "klaviyo-flow-automation", name: "Klaviyo Flow Automation", description: "Automate Klaviyo flows and email marketing.", category: "Marketing / Automation" },
  { id: "link-intersect-outreach", name: "Link Intersect Outreach", description: "Find and outreach to link intersect opportunities.", category: "SEO / Outreach" },
  { id: "local-seo-toolkit", name: "Local SEO Toolkit", description: "Tools for GMB, citations, reviews, and local rankings.", category: "SEO / Local" },
  { id: "ltv-churn-predictor", name: "LTV Churn Predictor", description: "Predict lifetime value and churn risk.", category: "Analytics / Retention" },
  { id: "multi-channel-optimizer", name: "Multi-Channel Optimizer", description: "Optimize marketing spend across channels.", category: "Marketing / Analytics" },
  { id: "on-page-seo-engine", name: "On-Page SEO Engine", description: "Optimize on-page SEO elements for better ranking.", category: "SEO / Automation" },
  { id: "personalization-recommendation-engine", name: "Personalization Recommendation Engine", description: "AI-driven recommendations for products and content.", category: "Personalization / AI" },
  { id: "product-seo-engine", name: "Product SEO Engine", description: "Generate SEO metadata for products.", category: "SEO / Automation" },
  { id: "rank-visibility-tracker", name: "Rank Visibility Tracker", description: "Track search rank and visibility for keywords.", category: "SEO / Analytics" },
  { id: "reporting-alerts", name: "Reporting Alerts", description: "Set up and manage reporting alerts and notifications.", category: "Reporting / Alerts" },
  { id: "reporting-integrations", name: "Reporting Integrations", description: "Integrate reporting with Slack, Teams, Email, and Push notifications.", category: "Reporting / Integration" },
  { id: "returns-rma-automation", name: "Returns RMA Automation", description: "Automate returns and RMA processes for e-commerce.", category: "E-commerce / Operations" },
  { id: "review-ugc-engine", name: "Review UGC Engine", description: "Generate and manage user-generated content reviews.", category: "Reviews / UGC" },
  { id: "scheduled-export", name: "Scheduled Export", description: "Schedule and automate PDF/CSV exports.", category: "Reporting / Export" },
  { id: "schema-rich-results-engine", name: "Schema Rich Results Engine", description: "Generate schema.org rich results for SEO.", category: "SEO / Automation" },
  { id: "self-service-portal", name: "Self-Service Portal", description: "Branded portal for merchants to manage integrations, billing, and support.", category: "Portal" },
  { id: "self-service-support-portal", name: "Self-Service Support Portal", description: "Support portal for merchants and customers.", category: "Support / Portal" },
  { id: "seo-site-crawler", name: "SEO Site Crawler", description: "Crawl and audit websites for SEO issues.", category: "SEO / Audit" },
  { id: "serp-tracker", name: "SERP Tracker", description: "Track search engine results page rankings.", category: "SEO / Analytics" },
  { id: "site-audit-health", name: "Site Audit Health", description: "Audit site health and performance for SEO.", category: "SEO / Audit" },
  { id: "social-media-analytics-listening", name: "Social Media Analytics & Listening", description: "Monitor and analyze social media performance and mentions.", category: "Analytics / Social" }
];

export default toolsMeta;
