// Auto-generated tool meta registry for Aura Core
// Each object: { id, name, description, category }


const toolsMeta = [
  { id: "abandoned-checkout-winback", name: "Abandoned Checkout Winback", description: "Generates abandoned checkout winback flows.", category: "Email / Automation" },
  { id: "ai-alt-text-engine", name: "AI Alt-Text Engine", description: "Generates AI-powered alt text for images.", category: "SEO / AI" },
  { id: "ai-launch-planner", name: "AI Launch Planner", description: "Creates launch plans for new products or collections.", category: "Marketing / AI" },
  { id: "ai-support-assistant", name: "AI Support Assistant", description: "Generates support macros and FAQ topics.", category: "Support / AI" },
  { id: "aura-api-sdk", name: "Aura API SDK", description: "Generates API SDK configuration snippets.", category: "Development" },
  { id: "aura-operations-ai", name: "Aura Operations AI", description: "Generates operations insights and checklists.", category: "Operations / AI" },
  { id: "auto-insights", name: "Auto Insights", description: "Automated high-level business insights.", category: "Analytics / AI" },
  { id: "blog-draft-engine", name: "Blog Draft Engine", description: "Generate a full SEO-focused blog article draft from a single blog idea.", category: "Content · Drafts" },
  { id: "blog-seo", name: "Blog SEO Engine", description: "Generate SEO titles, meta descriptions, slugs and keyword sets for blog posts and articles.", category: "SEO" },
  { id: "brand-intelligence-layer", name: "Brand Intelligence Layer", description: "Generates brand voice and intelligence snapshots.", category: "Brand" },
  { id: "creative-automation-engine", name: "Creative Automation Engine", description: "Generates creative hooks and angles.", category: "Marketing / Creative" },
  { id: "customer-support-ai", name: "Customer Support AI", description: "Assists with customer support tasks using AI.", category: "Support / AI" },
  { id: "daily-cfo-pack", name: "Daily CFO Pack", description: "Daily CFO summary and KPIs.", category: "Finance" },
  { id: "dynamic-pricing-engine", name: "Dynamic Pricing Engine", description: "Dynamic pricing logic and simulation.", category: "Pricing" },
  { id: "email-automation-builder", name: "Email Automation Builder", description: "Builds email automation flows and blueprints.", category: "Email / Automation" },
  { id: "finance-autopilot", name: "Finance Autopilot", description: "Automated finance snapshot and margin analysis.", category: "Finance" },
  { id: "image-alt-media-seo", name: "Image Alt / Media SEO", description: "Generates image alt text and media SEO recommendations.", category: "SEO" },
  { id: "inbox-assistant", name: "Inbox Assistant", description: "Assists with inbox management and replies.", category: "Support" },
  { id: "inbox-reply-assistant", name: "Inbox Reply Assistant", description: "Generates reply templates for customer support inbox.", category: "Support" },
  { id: "internal-link-optimizer", name: "Internal Link Optimizer", description: "Suggests internal links for SEO and navigation.", category: "SEO" },
  { id: "inventory-supplier-sync", name: "Inventory Supplier Sync", description: "Syncs inventory data with suppliers.", category: "Operations" },
  { id: "klaviyo-flow-automation", name: "Klaviyo Flow Automation", description: "Blueprints for Klaviyo automation flows.", category: "Email / Automation" },
  { id: "ltv-churn-predictor", name: "LTV / Churn Predictor", description: "Predicts lifetime value and churn risk.", category: "Analytics" },
  { id: "multi-channel-optimizer", name: "Multi-Channel Optimizer", description: "Splits marketing budget across multiple channels.", category: "Marketing" },
  { id: "on-page-seo-engine", name: "On-Page SEO Engine", description: "Optimizes on-page SEO elements.", category: "SEO" },
  { id: "product-seo", name: "Product SEO Engine", description: "Generate SEO titles, meta descriptions, slugs and keyword sets for products.", category: "SEO" },
  { id: "rank-visibility-tracker", name: "Rank & Visibility Tracker", description: "Tracks search rank and visibility.", category: "SEO" },
  { id: "returns-rma-automation", name: "Returns/RMA Automation", description: "Automates returns and RMA processes.", category: "Operations" },
  { id: "review-ugc-engine", name: "Review UGC Engine", description: "Generates review prompts and UGC questions.", category: "Reviews / UGC" },
  { id: "schema-rich-results-engine", name: "Schema Rich Results Engine", description: "Generates schema.org rich results snippets.", category: "SEO" },
  { id: "social-scheduler-content-engine", name: "Social Scheduler Content Engine", description: "Automates social content scheduling.", category: "Social / Content" },
  { id: "technical-seo-auditor", name: "Technical SEO Auditor", description: "Performs technical SEO health checks.", category: "SEO" },
  { id: "weekly-blog-content-engine", name: "Weekly Blog Content Engine", description: "Generate a simple weekly content plan with SEO-ready blog titles, meta descriptions, slugs and primary keywords.", category: "SEO / Content" },
  { id: "workflow-orchestrator", name: "Workflow Orchestrator", description: "Orchestrates multi-step automation workflows.", category: "Automation" }
  // --- New flagship tools and enhancements ---
  { id: "customer-data-platform", name: "Customer Data Platform (CDP)", description: "Unified customer profiles, segmentation, and omnichannel activation.", category: "Data / CRM" },
  { id: "visual-workflow-builder", name: "Visual Workflow Automation Builder", description: "Drag-and-drop workflow builder for cross-tool automations.", category: "Automation" },
  { id: "self-service-portal", name: "Self-Service Portal", description: "Branded portal for merchants to manage integrations, billing, and support.", category: "Portal" },
  { id: "advanced-personalization-engine", name: "Advanced Personalization Engine", description: "AI-powered real-time content/product personalization.", category: "Personalization / AI" },
  { id: "ab-testing-suite", name: "AI-Powered A/B Testing Suite", description: "Automated test setup, analysis, and optimization.", category: "Testing / AI" },
  { id: "data-warehouse-connector", name: "Data Warehouse/BI Connector", description: "Integrate with BigQuery, Snowflake, Looker, etc., for advanced analytics.", category: "Analytics / Integration" },
  { id: "consent-privacy-management", name: "Consent & Privacy Management", description: "Automated GDPR/CCPA compliance, consent tracking, and audit logs.", category: "Compliance" },
  { id: "entity-topic-explorer", name: "Entity/Topic Explorer", description: "Semantic SEO: discover entities and topics for your content.", category: "SEO / AI" },
  { id: "internal-linking-suggestions", name: "Automated Internal Linking Suggestions", description: "AI-powered suggestions for internal links to boost SEO.", category: "SEO / AI" },
  { id: "ai-content-brief-generator", name: "AI Content Brief Generator", description: "Instantly generate detailed content briefs with AI.", category: "Content / AI" },
  { id: "brand-mention-tracker", name: "Brand Mention Tracker", description: "Track brand mentions across the web and social media.", category: "Analytics / Brand" },
  { id: "local-seo-toolkit", name: "Local SEO Toolkit", description: "Tools for GMB, citations, reviews, and local rankings.", category: "SEO / Local" },
  { id: "automation-templates", name: "Prebuilt Automation Templates", description: "Ready-to-use workflow and automation templates.", category: "Automation" },
  { id: "conditional-logic-automation", name: "Conditional Logic & Branching", description: "Add conditional logic and branching to your automations.", category: "Automation" },
  { id: "webhook-api-triggers", name: "Webhook & External API Triggers", description: "Trigger automations from webhooks and external APIs.", category: "Automation / Integration" },
  { id: "reporting-integrations", name: "Reporting Integrations", description: "Integrate reporting with Slack, Teams, Email, and Push notifications.", category: "Reporting / Integration" },
  { id: "custom-dashboard-builder", name: "Custom Dashboard Builder", description: "Build custom dashboards for your reporting needs.", category: "Reporting / Visualization" },
  { id: "scheduled-export", name: "Scheduled PDF/CSV Exports", description: "Schedule PDF/CSV exports of your reports and dashboards.", category: "Reporting / Export" },
  { id: "churn-prediction-playbooks", name: "Churn Prediction & Retention Playbooks", description: "Predict churn and automate retention strategies.", category: "E-commerce / AI" },
  { id: "upsell-cross-sell-engine", name: "AI-Powered Upsell/Cross-sell Engine", description: "Boost revenue with AI-driven upsell and cross-sell recommendations.", category: "E-commerce / AI" },
  { id: "inventory-forecasting", name: "Inventory Forecasting", description: "Predict inventory needs and optimize stock levels.", category: "E-commerce / Analytics" },
];

export default toolsMeta;
