// Auto-generated tool meta registry for Aura Core
// Each object: { id, name, description, category }



// Unified and deduplicated tool meta registry
const toolsMeta = [
  { id: "main-suite", name: "Main Suite", description: "Unified entry point with grouped modules (workflows, analytics, SEO, personalization, lifecycle).", category: "Platform" },
  { id: "seo-master-suite", name: "SEO Master Suite", description: "Unified SEO platform consolidating 8 tools: keyword research, content analysis, schema markup, local SEO, entity explorer, on-page optimization, content scoring, and topic clustering. World-class enterprise features.", category: "SEO" },
  { id: "abandoned-checkout-winback", name: "Abandoned Checkout Winback", description: "Generates abandoned checkout winback flows.", category: "Email / Automation" },
  { id: "ab-testing-suite", name: "A/B Testing Suite", description: "A/B test creation, management, and analytics.", category: "Analytics" },
  { id: "ad-creative-optimizer", name: "Ad Creative Optimizer", description: "Generate and iterate ad creatives with AI.", category: "Ads / Marketing" },
  { id: "ads-anomaly-guard", name: "Ads Anomaly Guard", description: "Detect spend/performance anomalies across ad channels.", category: "Ads / Marketing" },
  { id: "advanced-analytics-attribution", name: "Advanced Analytics Attribution", description: "Advanced attribution analytics.", category: "Analytics" },
  { id: "advanced-finance-inventory-planning", name: "Advanced Finance & Inventory Planning", description: "Advanced financial and inventory planning analytics.", category: "Finance / Analytics" },
  { id: "advanced-personalization-engine", name: "Advanced Personalization Engine", description: "AI-powered real-time content/product personalization.", category: "Personalization / AI" },
  { id: "ai-content-image-gen", name: "AI Content & Image Gen", description: "Generate campaign copy and images for ads/email.", category: "Content / AI" },
  { id: "ai-segmentation-engine", name: "AI Segmentation", description: "Auto-discover high-value audiences and traits.", category: "Personalization / AI" },
  { id: "ai-content-brief-generator", name: "AI Content Brief Generator", description: "AI-powered content brief generation.", category: "Content / AI" },
  { id: "ai-alt-text-engine", name: "AI Alt-Text Engine", description: "Generates AI-powered alt text for images.", category: "SEO / AI" },
  { id: "ai-launch-planner", name: "AI Launch Planner", description: "Creates launch plans for new products or collections.", category: "Marketing / AI" },
  { id: "ai-support-assistant", name: "AI Support Assistant", description: "Generates support macros and FAQ topics.", category: "Support / AI" },
  { id: "aura-api-sdk", name: "Aura API SDK", description: "Generates API SDK configuration snippets.", category: "Development" },
  { id: "aura-operations-ai", name: "Aura Operations AI", description: "Generates operations insights and checklists.", category: "Operations / AI" },
  { id: "auto-insights", name: "Auto Insights", description: "Automated high-level business insights.", category: "Analytics / AI" },
  { id: "compliance-privacy-suite", name: "Compliance & Privacy Suite", description: "Consent, data export, and audit controls.", category: "Compliance" },
  { id: "automation-templates", name: "Automation Templates", description: "Templates for automation workflows.", category: "Automation" },
  { id: "backlink-explorer", name: "Backlink Explorer", description: "Explore and analyze backlinks for SEO.", category: "SEO" },
  { id: "blog-draft-engine", name: "Blog Draft Engine", description: "Generate a full SEO-focused blog article draft from a single blog idea.", category: "Content · Drafts" },
  { id: "blog-seo", name: "Blog SEO Engine", description: "Generate SEO titles, meta descriptions, slugs and keyword sets for blog posts and articles.", category: "SEO" },
  { id: "brand-intelligence-layer", name: "Brand Intelligence Layer", description: "Generates brand voice and intelligence snapshots.", category: "Brand" },
  { id: "brand-mention-tracker", name: "Brand Mention Tracker", description: "Track brand mentions across the web.", category: "Brand" },
  { id: "churn-prediction-playbooks", name: "Churn Prediction Playbooks", description: "Automated playbooks for churn prediction and retention.", category: "Analytics" },
  { id: "collaboration-approval-workflows", name: "Collaboration & Approval Workflows", description: "Automate collaboration and approval processes.", category: "Operations" },
  { id: "competitive-analysis", name: "Competitive Analysis", description: "Analyze competitors and market trends.", category: "Analytics" },
  { id: "conditional-logic-automation", name: "Conditional Logic Automation", description: "Conditional logic for automations.", category: "Automation" },
  { id: "consent-privacy-management", name: "Consent & Privacy Management", description: "Consent and privacy management tools.", category: "Compliance" },
  { id: "content-health-auditor", name: "Content Health Auditor", description: "Audit and improve content health and quality.", category: "Content / AI" },
  { id: "content-scoring-optimization", name: "Content Scoring & Optimization", description: "Score and optimize content for SEO and engagement.", category: "Content / AI" },
  { id: "creative-automation-engine", name: "Creative Automation Engine", description: "Generates creative hooks and angles.", category: "Marketing / Creative" },
  { id: "custom-dashboard-builder", name: "Custom Dashboard Builder", description: "Build custom dashboards.", category: "Analytics" },
  { id: "customer-data-platform", name: "Customer Data Platform", description: "Centralize and analyze customer data.", category: "Analytics / Integration" },
  { id: "customer-journey-mapping", name: "Customer Journey Mapping", description: "Map customer journeys.", category: "Analytics" },
  { id: "customer-segmentation-engine", name: "Customer Segmentation Engine", description: "Segment customers for analytics.", category: "Analytics" },
  { id: "customer-support-ai", name: "Customer Support AI", description: "Assists with customer support tasks using AI.", category: "Support / AI" },
  { id: "facebook-ads-integration", name: "Facebook/Instagram Ads Integration", description: "Sync campaigns, audiences, and performance from Meta.", category: "Ads / Marketing" },
  { id: "google-ads-integration", name: "Google Ads Integration", description: "Manage campaigns and audience sync for Google Ads.", category: "Ads / Marketing" },
  { id: "daily-cfo-pack", name: "Daily CFO Pack", description: "Daily financial insights and reports.", category: "Finance / Analytics" },
  { id: "data-enrichment-suite", name: "Data Enrichment Suite", description: "Data enrichment tools.", category: "Data" },
  { id: "data-warehouse-connector", name: "Data Warehouse Connector", description: "Connect to data warehouses.", category: "Data" },
  { id: "dynamic-pricing-engine", name: "Dynamic Pricing Engine", description: "Dynamic pricing optimization.", category: "Pricing" },
  { id: "email-automation-builder", name: "Email Automation Builder", description: "Automate email campaigns and flows.", category: "Marketing / Automation" },
  { id: "entity-topic-explorer", name: "Entity Topic Explorer", description: "Explore entity topics.", category: "SEO" },
  { id: "finance-autopilot", name: "Finance Autopilot", description: "Automate financial operations and reporting.", category: "Finance / Analytics" },
  { id: "image-alt-media-seo", name: "Image Alt Media SEO", description: "Optimize image alt text and media for SEO.", category: "SEO / AI" },
  { id: "inbox-assistant", name: "Inbox Assistant", description: "Automate inbox management and responses.", category: "Support / AI" },
  { id: "inbox-reply-assistant", name: "Inbox Reply Assistant", description: "Generate reply templates for support inbox.", category: "Support / AI" },
  { id: "internal-linking-suggestions", name: "Internal Linking Suggestions", description: "Suggest internal links.", category: "SEO" },
  { id: "internal-link-optimizer", name: "Internal Link Optimizer", description: "Suggests internal links for SEO and navigation.", category: "SEO" },
  { id: "inventory-forecasting", name: "Inventory Forecasting", description: "Forecast inventory needs.", category: "Operations" },
  { id: "inventory-supplier-sync", name: "Inventory Supplier Sync", description: "Syncs inventory data with suppliers.", category: "Operations" },
  { id: "keyword-research-suite", name: "Keyword Research Suite", description: "Comprehensive keyword research tools.", category: "SEO" },
  { id: "klaviyo-flow-automation", name: "Klaviyo Flow Automation", description: "Blueprints for Klaviyo automation flows.", category: "Email / Automation" },
  { id: "link-intersect-outreach", name: "Link Intersect & Outreach", description: "Find link opportunities and automate outreach.", category: "SEO" },
  { id: "local-seo-toolkit", name: "Local SEO Toolkit", description: "Local SEO optimization tools.", category: "SEO" },
  { id: "ltv-churn-predictor", name: "LTV / Churn Predictor", description: "Predicts lifetime value and churn risk.", category: "Analytics" },
  { id: "multi-channel-optimizer", name: "Multi-Channel Optimizer", description: "Splits marketing budget across multiple channels.", category: "Marketing" },
  { id: "omnichannel-campaign-builder", name: "Omnichannel Campaign Builder", description: "Orchestrate email, SMS, and ads in one flow.", category: "Marketing / Automation" },
  { id: "on-page-seo-engine", name: "On-Page SEO Engine", description: "Optimizes on-page SEO elements.", category: "SEO" },
  { id: "personalization-recommendation-engine", name: "Personalization Recommendation Engine", description: "AI-driven product/content recommendations.", category: "Personalization / AI" },
  { id: "product-seo-engine", name: "Product SEO Engine", description: "Generate SEO titles, meta descriptions, slugs and keyword sets for products.", category: "SEO" },
  { id: "rank-visibility-tracker", name: "Rank & Visibility Tracker", description: "Tracks search rank and visibility.", category: "SEO" },
  { id: "reporting-alerts", name: "Reporting Alerts", description: "Reporting and alerting tools.", category: "Analytics" },
  { id: "reporting-integrations", name: "Reporting Integrations", description: "Integrate reporting tools.", category: "Analytics" },
  { id: "predictive-analytics-widgets", name: "Predictive Analytics Widgets", description: "Churn, LTV, demand forecasts, and anomaly alerts.", category: "Analytics / AI" },
  { id: "returns-rma-automation", name: "Returns/RMA Automation", description: "Automates returns and RMA processes.", category: "Operations" },
  { id: "review-ugc-engine", name: "Review UGC Engine", description: "Generates review prompts and UGC questions.", category: "Reviews / UGC" },
  { id: "scheduled-export", name: "Scheduled Export", description: "Schedule data exports.", category: "Data" },
  { id: "schema-rich-results-engine", name: "Schema Rich Results Engine", description: "Generates schema.org rich results snippets.", category: "SEO" },
  { id: "self-service-portal", name: "Self Service Portal", description: "Customer self-service portal.", category: "Support" },
  { id: "self-service-analytics", name: "Self-Service Analytics", description: "Customizable dashboards and scheduled reporting.", category: "Analytics" },
  { id: "self-service-support-portal", name: "Self Service Support Portal", description: "Support self-service portal.", category: "Support" },
  { id: "seo-site-crawler", name: "SEO Site Crawler", description: "Crawl and audit SEO for sites.", category: "SEO" },
  { id: "serp-tracker", name: "SERP Tracker", description: "Track SERP rankings.", category: "SEO" },
  { id: "site-audit-health", name: "Site Audit Health", description: "Comprehensive site health and audit checks.", category: "SEO" },
  { id: "social-media-analytics-listening", name: "Social Media Analytics & Listening", description: "Monitor and analyze social media performance.", category: "Social / Analytics" },
  { id: "social-scheduler-content-engine", name: "Social Scheduler Content Engine", description: "Automates social content scheduling.", category: "Social / Content" },
  { id: "tiktok-ads-integration", name: "TikTok Ads Integration", description: "Sync audiences and creatives for TikTok Ads.", category: "Ads / Marketing" },
  { id: "technical-seo-auditor", name: "Technical SEO Auditor", description: "Performs technical SEO health checks.", category: "SEO" },
  { id: "tool-scaffold", name: "Tool Scaffold", description: "Scaffold for new tools.", category: "Development" },
  { id: "upsell-cross-sell-engine", name: "Upsell/Cross-Sell Engine", description: "Upsell and cross-sell recommendations.", category: "Sales" },
  { id: "visual-workflow-builder", name: "Visual Workflow Builder", description: "Visual builder for workflows.", category: "Automation" },
  { id: "webhook-api-triggers", name: "Webhook & API Triggers", description: "Webhook and API trigger management.", category: "Integration" },
  { id: "weekly-blog-content-engine", name: "Weekly Blog Content Engine", description: "Generate a simple weekly content plan with SEO-ready blog titles, meta descriptions, slugs and primary keywords.", category: "SEO / Content" },
  { id: "winback-empty-state", name: "Winback Empty State", description: "Winback empty state UI.", category: "Email / Automation" },
  { id: "winback-feature-card", name: "Winback Feature Card", description: "Winback feature card UI.", category: "Email / Automation" },
  { id: "winback-help-docs", name: "Winback Help Docs", description: "Winback help documentation.", category: "Email / Automation" },
  { id: "workflow-automation-builder", name: "Workflow Automation Builder", description: "Build and automate workflows across tools.", category: "Automation" },
  { id: "workflow-orchestrator", name: "Workflow Orchestrator", description: "Orchestrates multi-step automation workflows.", category: "Automation" }
];

export default toolsMeta;
